### ISSUE TITLE
Change packet delay to milliseconds when "Resend" is used

### ISSUE THREAD

**Issue by topiux** [dannagle/PacketSender#10]
Specifying packet delay in milliseconds instead of seconds might be beneficial. Additionally "Delay" as the label for the input field might be more appropriate as "Resend" suggests more the number of packets to be resent (which is not a bad feature to implement as well)

**Comment by dannagle** [comment]
Milliseconds has been asked for before. It would be really difficult to get the engine down to that level of fidelity. Resend was a bolted-on feature to the UI. 

I could start with allowing 1 decimal place in seconds and gradually work it down to 2 decimal places. That's about the best it could do without major rework.

**Comment by topiux** [comment]
Thanks Dan. Sounds like a plan. Any comment on my other enhancement request about multi-send mode?

**Comment by dannagle** [comment]
Just pushed to the master branch. The next version of Packet Sender will support 1 decimal place (100 milliseconds) for resend.

**Comment by dannagle** [comment]
The development branch is at 90 ms, so not much faster.  If I had a day of refactoring, I could make resend really fast and more accurate, but that is not going to be a priority unless that feature gets a sponsor.
