### ISSUE TITLE
The maximum size of UDP is 1024

### ISSUE THREAD

**Issue by AndrewJYAndrew** [dannagle/PacketSender#100]
Hi,

This is a great tool to help me verify my UDP service.

However, when I send a file to a UDP port from command line, there is a limit to 1024.  When I did it in the GUI, there is no such limit.  Can this limit in command line extend to over 9000 or current MTU size?

Thanks.

**Comment by dannagle** [comment]
I found where I hard-coded the max size. I did it as a workaround to a memory problem (which I have since solved). It's now set to 10 MiB. I'll close this ticket next time I build new installers.

**Comment by AndrewJYAndrew** [comment]
What a quick response!! 

Thanks a lot.

**Comment by dannagle** [comment]
Installers now live.
