### ISSUE TITLE
performance testing tool

### ISSUE THREAD

**Issue by xiaopangtage** [dannagle/PacketSender#102]
I'm sorry for that my english is not good . 
i need a performance testing tool. i wonder if the packetSender could send packet in a high-performance mode such as  reaching the max bandwith of interface  or high concurrency ？

**Comment by dannagle** [comment]
It'll be difficult to make Packet Sender flood your interface. Packet Sender's max interval is 100ms. The tool uses multithreading, so you may can get higher. Still, that is a little slow for network traffic. 

However, you can launch multiple instances of Packet Sender (using port 0) and use the "resend" feature to generate a pile of concurrent commands. I've used this to stress a target server. I recommend turning off logging if you do this. 

It is not a precise test, but that may do what you need.
