### ISSUE TITLE
Release Appx for Win10

### ISSUE THREAD

**Issue by deinok** [dannagle/PacketSender#104]
Deploy PacketSender as a AppX package.
Also, this will allow you to release to windows store

**Comment by dannagle** [comment]
Interesting idea, but it probably won't happen. Several problems:

1. UWP's has strict rules regarding network connections that may prevent Packet Sender from doing its job. 

1. UWP also has strict rules for multi-threading, which Packet Sender may be violating. 

1. I don't own any ARM-based Windows devices, so it'd have to be x86/x64 only (which I already support outside the store).

Overcoming those obstacles is a significant level of effort which I don't have the resources right now.

**Comment by deinok** [comment]
I think that if you only target x86/x64 and only PC version, this can be done.

Take a look at https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root 
Seems like most of the third party installers already support this option.

And under this conditions network/threading rules dont afect

**Comment by dannagle** [comment]
Yes, this is looking more promising:
https://docs.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-prepare

What do you see as the benefit of having Packet Sender in the Windows Store and/or as an AppX? 

I personally never use the store, so I am hesitant at paying $99/year for a fairly specialized app that I give away for free.

**Comment by deinok** [comment]
Well, I think Appx as it is simplificates the process of Installing and Uninstalling, seems an upgrade of MSI installers.

About Windows Store, im not sure if you should pay 99$ for free apps. Even, if you are required to pay, I can give you a key to create a free users. (They come from my university)

**Comment by dannagle** [comment]
I appreciate the offer, but I'd want to register with my LLC. 

I don't think the windows store is compelling enough. For cases where a normal .exe installer will not work, I already offer a portable zipped version that is even easier to use than AppX.

**Comment by deinok** [comment]
Then, im closing this issue, atleast for now. Thanks for the fast responses ;)
