### ISSUE TITLE
Persistent TCP server does not use smart responses

### ISSUE THREAD

**Issue by urscion** [dannagle/PacketSender#108]
#### What OS?

- [ ] Windows
- [ ] Mac
- [X ] Linux (CentOS 7)

#### Description of issue

When using a persistent TCP connection, the server does not use the smart responses more than once (after initial packet receive.) I believe this is because the processing loop does not call the writeResponse function after receiving a packet.

**Comment by dannagle** [comment]
Just tested. Indeed, it does not. 

I'm flagging this as "enhancement" until I decide what to do. My particular use requires that it does not repeat. If I need the response again, I'd reconnect. I am not sure what is preferred.  The entire smart response engine could use some rework for the various open issues.

**Comment by urscion** [comment]
Ok, no worries. I have it changed locally for my use case so if i get desperate I can either work with you or submit a pull request myself.

**Comment by dannagle** [comment]
Fixed in development branch.

Leaving this thread open as a reminder to ping it one more time when development is eventually merged into master.

**Comment by dannagle** [comment]
wow. i fixed this ticket and left it open for 3 years.
