### ISSUE TITLE
Repeating period and numbers of  "resend" function

### ISSUE THREAD

**Issue by wgxdz** [dannagle/PacketSender#11]
1. Increase the resending rates more than once per second would be beneficial for high volume packet testing.

2. Add an option to define total # of repeat, it will be helpful for automated testing. For example, we can set "Resend every 1 sec", and then set "Resend 300 times". So PacketSender will send the packet once per second, and stop sending after 300 packets have been sent.

**Comment by topiux** [comment]
These two enhancements are mentioned in issue #10

**Comment by dannagle** [comment]
Support for request 1 was just pushed to the master branch. The next version of Packet Sender will support 1 decimal place (100 milliseconds).

**Comment by dannagle** [comment]
Added "Cancel resending after X packets". It is a global setting. Currently available in the development branch.

**Comment by dannagle** [comment]
Cancel after resend now in master branch. Also fixed a bug related to 0.X resend timing.
