### ISSUE TITLE
Is it possible to cancel redending packets individually?

### ISSUE THREAD

**Issue by RamonR78** [dannagle/PacketSender#111]
#### What OS?

- [x] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

Is it possible to implement that the resending of packets can be canceled individually, e.g. replacing/toggeling the send button, when packets are resend?

BTW
 You've done a great job sofar, thanks!

![packetsender](https://user-images.githubusercontent.com/37801525/37905915-bd58c40a-3100-11e8-848c-a533207e9822.png)

**Comment by dannagle** [comment]
It cancels all of them. I could not think of an easy UI mechanism for individual canceling. I decided that was a an edge case few would need. Looks like you need it. There currently isn't a plan to add it.  

Here is how I would do it:

* Your device probably does not need both the source and the target to be 60000. 
* Therefore, set the port bind be dynamic (set it to 0). 

Now, you can launch 2 (or more) Packet Senders each resending so you can cancel.
