### ISSUE TITLE
Space character added when trying to send UDP packet

### ISSUE THREAD

**Issue by Omcsesz** [dannagle/PacketSender#112]
#### What OS?

- [X] Windows 7
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

When trying to send an UDP packet, a space character gets added to the data to be sent (see gif).
![packet sender udp data bug](https://user-images.githubusercontent.com/1839739/38177479-afc1d3f2-3602-11e8-943d-17253c1fbfe4.gif)

**Comment by dannagle** [comment]
This is working correctly. The standard format for Packet Sender hex notation is to have spaces between each bytes. It accepts many delimiters for the bytes, including no delimiter like your example, and it will convert it to the space-delimited format.

**Comment by Omcsesz** [comment]
I see.
So it can be closed now.
