### ISSUE TITLE
Crash in ArchLinux

### ISSUE THREAD

**Issue by fragrans** [dannagle/PacketSender#113]
Linux (Archlinux)
#### Description of issue

![image](https://user-images.githubusercontent.com/102768/38762674-02e8cae6-3fc1-11e8-8419-e09642356cb2.png)

Update:
I have to build it from source, and it just works like a charm.

**Comment by dannagle** [comment]
This does not surprise me. It's a compiled binary from an Ubuntu-based distro. There are too many flavors of Linux to provide binaries for all. Perhaps I should clarify the web site.

**Comment by dannagle** [comment]
An Arch-based distro with Packet Sender:
https://archstrike.org/packages/packetsender

Maybe compiling from source with their build log will help you.
