### ISSUE TITLE
Get IP-address out of commandline response

### ISSUE THREAD

**Issue by MrDennis21** [dannagle/PacketSender#114]
#### What OS?

- [X] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

{I'm using packetsender from the commandline (batch) for using udp packets. Works fine. But what I am missing in the response answer of packetsender is the ip-address of the sender of the answer. This naturally information is shown at the windows-version of packetsender, but not at the commandline. Is there a way to get the ip-address out of received responses at the commandline?}

**Comment by dannagle** [comment]
Now in the development branch. Will be released on next version.
