### ISSUE TITLE
macOS 10.14 dark theme issue

### ISSUE THREAD

**Issue by HAWK0044** [dannagle/PacketSender#115]
#### What OS?

- [ ] Windows
- [*] Mac
- [ ] Linux (Which distro?)

#### Description of issue

Text on labels is not visible in new macOS 10.14 Mojave while using Dark Theme

**Comment by dannagle** [comment]
Will you please give this pre-release a test to see if it works better?
https://github.com/dannagle/PacketSender/releases/tag/v5.7.4


I fixed dark theme on Linux by turning off all my custom styling. I've now turned it off for Mac too.

**Comment by HAWK0044** [comment]
Thanks, yes it's partially works on 5.7.4
Main labels' texts are visible, but other aren't.
<img width="910" alt="image" src="https://user-images.githubusercontent.com/7602930/41204743-3fa8f9c6-6cf1-11e8-807b-c47e40fab0a4.png">

**Comment by HAWK0044** [comment]
Better. 
Now problem appears for combos and buttons:
<img width="905" alt="image" src="https://user-images.githubusercontent.com/7602930/41205270-11d8c9ec-6cf9-11e8-84bf-7d64b9ddd721.png">

**Comment by HAWK0044** [comment]
Better, now it appears for combos and buttons:
<img width="907" alt="image" src="https://user-images.githubusercontent.com/7602930/41205278-3039bc20-6cf9-11e8-925f-6c9d1cccd3ea.png">

**Comment by HAWK0044** [comment]
Btw, if this app's interface built with XCode, you might try XCode 10 beta, this one should support dark theme

**Comment by dannagle** [comment]
It does not use XCode. The GUI library I am using (Qt) will likely eventually have built-in support for mac dark mode, but until then, I have tweak these manually.

Another tweak when you get a chance:
https://github.com/dannagle/PacketSender/releases/tag/v5.7.6

**Comment by HAWK0044** [comment]
Almost ideal sadly Qt CSS can't customise combos to fancy appearance and they looks win2k alike:
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/7602930/41205879-1c82470a-6d04-11e8-9ff8-443863431df8.png">

**Comment by dannagle** [comment]
Goal 1 is to get this usable. Goal 2 will be to make it look nicer.

Tweaks for settings widgets:
https://github.com/dannagle/PacketSender/releases/tag/v5.7.7

**Comment by HAWK0044** [comment]
Good, now it's usable, thank you :)

**Comment by dannagle** [comment]
Thank you for helping to test.

**Comment by HAWK0044** [comment]
Hello,
New version looks much better than previous on macOS Mojave 10.14.2 (should be release, but I'am not sure)

There are some minor issues:
1. I believe this icons should be white
<img width="512" alt="image" src="https://user-images.githubusercontent.com/7602930/50533074-dcf82b80-0b33-11e9-85f7-20b7b17638f2.png">
2. Some buttons are bright instead of dark:
<img width="484" alt="image" src="https://user-images.githubusercontent.com/7602930/50533086-13ce4180-0b34-11e9-854b-8fbbf3b29075.png">
That's all I've noticed, application looks consistent for dark theme now. With light theme everything is good. I can even change theme when application is open, transition works as expected.

**Comment by dannagle** [comment]
Thanks for the feedback. I'll try to look in to those for the next round.

There are some issues I am still trying to figure out (like my specialized buttons staying bright), but I did not want to keep away this release when this dark theme update is such a significant improvement over what was previously out there.
