### ISSUE TITLE
IPv4 or IPv6?

### ISSUE THREAD

**Issue by bestpika** [dannagle/PacketSender#12]
Hello. I have a question.
The [From IP] is ::ffff:aaa.bbb.ccc.ddd.
What [IP Address] I would input?
Is aaa.bbb.ccc.ddd or ::ffff:aaa.bbb.ccc.ddd?

Thanks.

**Comment by dannagle** [comment]
IPv6 uses colons to separate the address bytes. 

The easiest way to get the IPv6 address (assuming Mac or Linux) is to run 
````
ifconfig 
````
on the command line. Copy the full address and paste it in to the to address. 

Screenshot using my local address. 

<img width="512" alt="ipv6_example" src="https://cloud.githubusercontent.com/assets/1140573/9696333/c484c722-5333-11e5-9cb9-e17811984623.png">
