### ISSUE TITLE
version numbers missing on macOS

### ISSUE THREAD

**Issue by core-code** [dannagle/PacketSender#122]
i've downloaded Version '5.7.52' but when selecting it in the Finder and using 'Get Info' it doesn't show any Version-number at all, instead it shows 'Created by QT'. i guess the CFBundleVersion and CFShortVersionString entries in your Info.plist file are missing.

**Comment by dannagle** [comment]
Indeed, you are correct. I'll flag this as a bug. 

You can get the version in the about window or --version in the command line.

**Comment by core-code** [comment]
thanks, i can confirm this is fixed in v6.1.25
