### ISSUE TITLE
UDP not sent as long UDP server is disabled

### ISSUE THREAD

**Issue by jeffrson** [dannagle/PacketSender#127]
Hi,

#### What OS?

- [ X] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

Version 5.7.52.

#### Description of issue

I want to send UDP packages.

As it seems, nothing is sent as long as the UDP server in PacketSender is disabled.

**Comment by dannagle** [comment]
I never considered the idea of sending UDP without a server. There would be no way of knowing if the packet reached its destination since it cannot receive a response. I suppose there is a use --you want to send and discard responses.

**Comment by dannagle** [comment]
This is now in the development branch.
