### ISSUE TITLE
Join UDP multicast group prompt

### ISSUE THREAD

**Issue by JanC** [dannagle/PacketSender#129]
#### What OS?

- [ ] Windows
- [x] Mac
- [ ] Linux (Which distro?)

#### Description of issue
Hi,
first of all thanks for this great tool.

Since the version `v5.8.5`, when I send a udp packet to a multicast IP, I keep getting the "Join UDP multicast group" prompt. I just want to send a packet to that multicast without necessarily joining it. In previous versions it was possible. Is there a way to disable that prompt once I choose "no" ?

cheers

**Comment by dannagle** [comment]
Currently, no. I assumed sending a packet without first joining the group would always be an error, but I suppose there are situations that you wish to just send. 

I'll fix it in the next version. Sorry.

**Comment by dannagle** [comment]
This fix should be in the latest release now. It now prompts just once per address per session.
