### ISSUE TITLE
how to send return code into package.. 

### ISSUE THREAD

**Issue by carlos-andres** [dannagle/PacketSender#13]
Good day, 

I'm running a socket to which I send a command line but in the end requires the use carriage return, I tried with \ r \ n  or chr (13). chr (10). chr (0) and has not been able to send the package  the return code.

![sin titulo](https://cloud.githubusercontent.com/assets/5489747/9801233/71b24724-57d7-11e5-85c2-63240695cd81.png)

thanks

**Comment by dannagle** [comment]
Since you closed the issue, I'll just offer this quick tip: If you are having problems with unexpected results, you could try a persistent connection. The default mode of Packet Sender is to close all connections.
