### ISSUE TITLE
Command line does not work on Mac 10.11 (v5.8.6)

### ISSUE THREAD

**Issue by dade80vr** [dannagle/PacketSender#136]
#### What OS?
- [x] Mac 10.11.6

#### PacketSender Version TAG?
- [x] v5.8.6 _(v6 does not work on 10.11)_

#### Description of issue

When i try to use the command line from `/Applications/PacketSender.app/Contents/MacOS`  nothing happened. The command name works on GUI.

`./PacketSender -n PJLINK-OFF`

Reply: `TCP (XXXXX)://192.168.0.XXX:4352 25 31 50 4F 57 52 20 30 0D`

No firewall or other filter sw actived.
How can i do? 
Many thanks

**Comment by dannagle** [comment]
You need to add a -w statement if you want it to listen for a reply. You can also try the full command, such as...

`
Dans-MacBook-Pro:MacOS dannagle$ ./PacketSender -taw 500 packetsender.com 80 "Hello\nWorld\n"
`

**Comment by dade80vr** [comment]
Thanks @dannagle but i cannot receive the SEND command to destination host, not the reply.
Same command via GUI works fine and the remote host receive packet/s.

**Comment by dannagle** [comment]
Did you try sending the command by explicitly stating all the parameters: -taw 500 192.168.1.13 5000 "my\ndata\n" ?  Perhaps there is something strange happening in the "-n" logic.

**Comment by dade80vr** [comment]
Hi @dannagle , you are right, it's work!

`./PacketSender -taw 500 192.168.0.94 4352 "%1POWR 1\r"`

It's power ON a projector via PJLINK protocol.
Something does not work fine with "-n" on my Mac (version v5.8.6)

**Comment by dannagle** [comment]
Glad it works for you. I'll label this ticket bug to look at further.

**Comment by dannagle** [comment]
This fix is now in the development branch.
