### ISSUE TITLE
[Question] Can send WOL - Magic Packet ?

### ISSUE THREAD

**Issue by dade80vr** [dannagle/PacketSender#137]
#### What OS?

- [ ] Windows GUI

#### Description of question

I built an HEX packet corresponding WOL specs (6 bytes FF + 16 times destination MAC address), put address 255.255.255.255, port 9, UDP protocol but i cannot wake up a computer in the same lan.

With another app WOL works great, but i can't use the command line so i prefer to use PacketSender. 
Thank you

**Comment by dade80vr** [comment]
Solved! Only a black space too much!

**Comment by dannagle** [comment]
FYI, this is now in the latest release.
