### ISSUE TITLE
Bind TCP Client on specific port

### ISSUE THREAD

**Issue by M-Razavi** [dannagle/PacketSender#14]
Hi 
I want to run a client which bind to predefined port.I winder if there is a solution to set port in GUI mode.

Thanks in advance

**Comment by dannagle** [comment]
The GUI supports connecting to multiple servers at a time. Each instance needs its own port. This could be added if it could fallback to dynamic bind if the port is already consumed.

**Comment by M-Razavi** [comment]
If each instance of application(GUI) was a client, Set a local(bind)  port for each one wouldn't cause a problem. Isn't true?
(I've used Hercules for my development test, but it hasn't this feature and couldn't bind client on a predefined port, so I'm going to use your application if it will developed)

**Comment by dannagle** [comment]
Correct, as long as each has its own port it will be fine. This would not be difficult to add. I just need to find a clean way to do it. I have an idea. Perhaps a user-defined starting port. For example, if requested, it start at 1000 and then count upward as ports are consumed.

**Comment by M-Razavi** [comment]
I suggest TCP Client domes default with one of system IP (in a combo-box) and dynamic port(a check box), If user wants, changes the IP and set a port(in a appeared text box ).

**Comment by dannagle** [comment]
Packet Sender now defaults to dynamic port (zero). This seems to be accepted standard for port allocation.
