### ISSUE TITLE
Zillya reports Trojan:Win32/Reconyc

### ISSUE THREAD

**Issue by cwimsatt** [dannagle/PacketSender#140]
#### What OS?

- [ X] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue
Steps to reproduce:
1) Download packetsender windows (non-portable)
2) Run VirusTotal.com scan

Expected behavior:
no detections

Actual behavior:
detected malware Trojan:Win32/Reconyc
https://www.virustotal.com/#/file/8ef07b3427308ef92f6b9854eaf63a9bb035011c57618d87559df7210822731e/detection
{{replace this}}

**Comment by dannagle** [comment]
My guess is the built-in TCP server is throwing it off. Antivirus really do not like software that launches an externally-available TCP server. Doing so is critical for Packet Sender to run.  

The source code is provided here on GitHub if you would like to try to rework it without a TCP server. It can be done with about an hour of configuring. That version may pass Zillya.
