### ISSUE TITLE
[Feature] Make "Append \r" in send window configurable

### ISSUE THREAD

**Issue by PaulFocus** [dannagle/PacketSender#141]
#### What OS?

not applicable

#### Description of issue

When using a persistent connection, the opened window will always start with the option **Append \r** being checked. 
Either the default value of this option could go to Settings
or
the last state (checked/unchecked) should be used.

**Comment by dannagle** [comment]
I like this idea.

My vote goes to remembering the last state. It's clean, intuitive, and does not require another entry in the settings window. That window is getting pretty busy.

**Comment by dannagle** [comment]
This is now in the development branch. 

Settings UI was not updated. The checkbox simply remembers the last state across instances. If you have multiple persistent windows open, it will remember the latest click.
