### ISSUE TITLE
CMakeLists.txt may mistake a parameter

### ISSUE THREAD

**Issue by tan-wei** [dannagle/PacketSender#143]
#### What OS?

- [x] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

Firstly, thanks for this awesome tool. I find a small mistake in `CMakeLists.txt` (line 54):
```cmake
add_executable(
  ${PROJECT_NAME}
  ${srcs_qrc}
  ${moc_uis}
  ${moc_uis}
  ${PACKETSENDER_SRCS}
)
```
A duplicated `moc_uis` may be `moc_srcs`, then it can work with some link errors.

**Comment by tan-wei** [comment]
So I corrected the `CMakeLists.txt` file in order to work with the new sources. It works well in my computer, just add some missing files to correct this.
[CMakeLists.txt](https://github.com/dannagle/PacketSender/files/3062132/CMakeLists.txt)

**Comment by dannagle** [comment]
Thanks for the pull request. Closing this issue.
