### ISSUE TITLE
Does Packet Sender support sending unicode data?

### ISSUE THREAD

**Issue by ychawla** [dannagle/PacketSender#146]
#### What OS?

- [ X] Windows

#### Description of issue

I am hitting a server that expects the packet data to be encoded using Unicode. Right now I think the default is to send the data encoded using Ascii. Using the Windows GUI for packet sender (or the command line), is it possible to encode the data using Unicode rather than Ascii?

**Comment by dannagle** [comment]
Yes, it can, indirectly.

Packet Sender has a HEX notation which is agnostic to any format. Hex can be typed in directly. 

Packet Sender also has a "Load File" feature (button is to the right of HEX notation) that can load any file of any format. You can use an external editor to create that file then load it with Packet Sender.

**Comment by ychawla** [comment]
Thanks for the explanation!
