### ISSUE TITLE
Dynamic Port

### ISSUE THREAD

**Issue by prashantchandak7** [dannagle/PacketSender#147]
#### What OS?

- [ ] Windows
- [y ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

The client a hardware sends packets to packet sender set as server on Mac. 

How can I configure packet sender to send packets on port number same as received from client?

Please note client changes port randomly.

<img width="906" alt="Screen Shot 2019-04-29 at 6 57 45 PM" src="https://user-images.githubusercontent.com/47504533/56899308-c4cbf500-6ab0-11e9-9668-6bf866d8203b.png">

**Comment by dannagle** [comment]
That is how TCP normally works. The source port is always dynamic while the target port of the server remains fixed. 

You can set Packet Sender's server port using (on Mac) PacketSender --> Preferences. 

<img width="256" alt="mac-preferences" src="https://user-images.githubusercontent.com/1140573/56900710-c2f53800-6a96-11e9-8fc7-233ba0cb6dcd.png">

Then changing the server port away from zero (which means random). 

<img width="518" alt="mac-tcp-server-choice" src="https://user-images.githubusercontent.com/1140573/56900721-cb4d7300-6a96-11e9-8205-00fabf5235f4.png">


If your testing requires a fixed source port when using TCP, you may do so on the command line using the -b option.

**Comment by prashantchandak7** [comment]
How can I bind port?

**Comment by dannagle** [comment]
Navigate to the executable. Assuming default location, it is here:
`
cd /Applications/PacketSender.app/Contents/MacOS/
`

This example command says to use hex notation, waits 500 ms for a response, binds source port to port 5000, and sends to address 127.0.01, port 15000, hex stream AA BB CC DD EE FF,  using TCP.

`
./PacketSender -x -w 500 -b 5000 127.0.0.1 15000 "aa bb cc dd ee ff"
`

You can use "--help" to get the complete help output.

**Comment by prashantchandak7** [comment]
I am getting an error. I do not have any defined port on client to respond to or the option is to reply back on same port from which I receive request from client. 

<img width="650" alt="Screen Shot 2019-04-29 at 8 21 56 PM" src="https://user-images.githubusercontent.com/47504533/56904668-63aa1e80-6abc-11e9-90f9-a8ad30519179.png">

**Comment by dannagle** [comment]
You left out the target port number. It goes after IP address.

**Comment by prashantchandak7** [comment]
Please see TCP flow data. 192.168.1.21 is server and 192.168.1.5 is client.

 The server/source IP port needs to be binded and  destination IP port needs to be dynamic based on the port from which client is requested to create a socket.

Is it possible to configure this in packet sender?

<img width="1183" alt="Screen Shot 2019-04-30 at 1 14 28 AM" src="https://user-images.githubusercontent.com/47504533/56922204-40479980-6ae5-11e9-9971-e028c8a49086.png">

**Comment by dannagle** [comment]
If you want to use a fixed port for both source and destination port for TCP (like Packet Sender does for UDP), the only way to do this is through the command line interface using the -b option. 

Packet Sender's UDP source and client is a fixed port on both sides because that is the only reliable way to collect responses. TCP does not need that since it is session-based. The GUI client for TCP will always request a dynamic port to connect a client to a server. This is how normal TCP operates, which is why your specialized use case is on the command line only (at least it is for now --you are not the first user needing to do this test).

**Comment by prashantchandak7** [comment]
Ok, but the client changes port every 5 minutes - so it is not possible to type manually destination port unless it can pick dynamically.

**Comment by dannagle** [comment]
With the server and client ports frequently changing, you will need to write scripting logic around the command line interface. Packet Sender cannot solve a setup this complicated by itself.
