### ISSUE TITLE
Does PacketSender support UDP bind to specified address, i.e. 192.168.1.100, 10.0.74.2 ?

### ISSUE THREAD

**Issue by GreatFireWall** [dannagle/PacketSender#148]
#### What OS?

- [1] Windows 
- [ ] Mac
- [ ] Linux (Which distro?)

**Comment by dannagle** [comment]
No, it only does a general bind. It either does "0.0.0.0" for IPv4 or "::" for IPv6.

However, I agree having IP-specific bind would be useful.

**Comment by GreatFireWall** [comment]
If add this feature to website release, please @me, thank you.
I'm so sorry I haven't QT IDE, so I can add this feature even I very need it. :(

**Comment by dannagle** [comment]
IP-specific binding is now in the development branch. 

The new bind choices are IPv4, IPv6, or your own custom IP (that can be either v4 or v6).

**Comment by dannagle** [comment]
@GreatFireWall

**Comment by GreatFireWall** [comment]
Great, thanks :)
