### ISSUE TITLE
Send a single packet on an open TCP connection (by another server). Merge/split ports?

### ISSUE THREAD

**Issue by OneBobone** [dannagle/PacketSender#149]
#### What OS?
- Windows 7
#### Description of issue
I would like to jump into an ongoing TCP connection between a server and client and send a single packet.  I.e. merge new traffic with the original port.
Would be very thankful for any help on this issue.

The traffic on the connection is low with little risk for conflict.
I cannot modify the main server's nor client's configuration (packaged SW).

**Comment by dannagle** [comment]
TCP is a one-to-one protocol.. What you are attempting is TCP session hijacking. Packet Sender does not support this. 

Something like you are attempting could be done if both connections were going to a server, and that server then merged the data in to a single stream going to a target. A similar idea has been proposed with ticket #75 .

**Comment by OneBobone** [comment]
Thank you very much for responding.
Yes, I suppose you are right, it is a sort hijacking that I need to do.
I need to send a status report to a client to trigger a request from the server.
