### ISSUE TITLE
Add size attribute to the log window

### ISSUE THREAD

**Issue by kslbeso** [dannagle/PacketSender#15]
I would appreciate if you would add a length attribute in (both the send and) the log part of the GUI.
That way it would be easier to be able to verify how many actual characters are being sent and received.

**Comment by dannagle** [comment]
Development branch now has a tooltip showing the data size upon hovering. 
<img width="320" alt="packetsendertooltip" src="https://cloud.githubusercontent.com/assets/1140573/11611180/9e74698a-9b85-11e5-8094-b7f01c3def0b.png">

**Comment by kslbeso** [comment]
Excellent! Looking forward to check it out!
Thanks!

**Comment by dannagle** [comment]
New installers are now live!
