### ISSUE TITLE
Packet Sender Cloud not save packets 

### ISSUE THREAD

**Issue by GreatFireWall** [dannagle/PacketSender#150]
#### What OS?

- [ 1] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

![image](https://user-images.githubusercontent.com/4510984/57193477-fc81e380-6f6d-11e9-8de0-1eb62c2f6a74.png)

![image](https://user-images.githubusercontent.com/4510984/57193456-c6dcfa80-6f6d-11e9-8dce-0eeaf84bb427.png)

![image](https://user-images.githubusercontent.com/4510984/57193467-db20f780-6f6d-11e9-929e-ed4c9732ac7c.png)

![image](https://user-images.githubusercontent.com/4510984/57193468-e2e09c00-6f6d-11e9-9d8d-f16a5231f5f0.png)

**Comment by dannagle** [comment]
I'm looking through the most recent database transactions, and I do see an oddity. I'm searching for the root cause now. Did you use non-ascii characters somewhere in that data set? I think that may have confused it.

**Comment by GreatFireWall** [comment]
Yes, I use some Chinese.

![image](https://user-images.githubusercontent.com/4510984/57195033-60ada300-6f80-11e9-8f7d-e2974530b78d.png)

**Comment by dannagle** [comment]
I can't seem to recreate the problem. 

If the data is not sensitive, will you email your database to hello@packetsender.com ?

File->Export Database

**Comment by GreatFireWall** [comment]
Sure, I have sent.

**Comment by dannagle** [comment]
I think I found the problem on the server. Try to save again.

**Comment by GreatFireWall** [comment]
Great, saving is success, but after import, some non-ascii chars become `???`.
I think use UTF-8 both client and server will be solved.

![image](https://user-images.githubusercontent.com/4510984/57214777-99e82080-701d-11e9-91eb-020c58f7dbf3.png)

**Comment by dannagle** [comment]
At least it is improved. Perhaps I should buy a non-ASCII keyboard for testing.

**Comment by GreatFireWall** [comment]
No, I use standard US ASCII keyboard too. 
You only need to add another language keyboard with IME(input method editor) in your system.

![gif](https://i.vgy.me/QOPJRR.gif)

**Comment by dannagle** [comment]
I found the bug causing the garbled name. As you predicted, it was an UTF-8 encoding problem. This fix required a change to Packet Sender itself, It'll be in the next release.

**Comment by dannagle** [comment]
This fix is now in the development branch.
