### ISSUE TITLE
it will automatically end the socket after every sending?

### ISSUE THREAD

**Issue by zzzgit** [dannagle/PacketSender#153]
![image](https://user-images.githubusercontent.com/1060733/58845107-7cee4e00-86ac-11e9-9a6b-1e003378e805.png)

Every time I hit this button, the client will connect to the server and then send the message and then receive from the server and then close the socket.

Yet I want it to keep the socket being connected, is it possible?

**Comment by dannagle** [comment]
Check the "Persistent TCP" checkbox just below in your picture. 

Then the connection will stay open, for both server and client.
