### ISSUE TITLE
Not Sending UDP

### ISSUE THREAD

**Issue by udsl** [dannagle/PacketSender#155]
#### What OS?

- [X ] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

{{Was working well till last update, now does not send UDP. Created Java app to send and target responds as expected but sending from PacketSender target does not respond.
Debugging target nothing is received  but socket when PacketSender used, packet received as expected when send from Java test app.

Have deleted and reinstalled PacketSender same result.}}

**Comment by dannagle** [comment]
- Have you tried setting port bind to 0 and making sure IPv4 toggle (bottom right) is set to IPv4, assuming that is what you are using?

- Have you tried the portable version (in case main version got corrupted)?

- If that doesn't work, may I see a screenshot of the main GUI and the network settings?

**Comment by rinripper** [comment]
Same problem here, I had the old version (without multicast tab) working well. I updated, and damage the UDP Tx function. I tried the portable version too without success

**Comment by dannagle** [comment]
Try tapping the IPv4 toggle to in the bottom right a couple times. Make sure your UDP bind is set 0. You can also try setting the bind address to your own IP address.

**Comment by dannagle** [comment]
Closing this ticket. 

Previous release had a bug that found UDP to not work properly for fresh out-of-the-box installations. There was a bad default value set. The bug self-corrected once any network setting at all was configured.
