### ISSUE TITLE
{{RANDOM}}

### ISSUE THREAD

**Issue by kropochev** [dannagle/PacketSender#159]
#### What OS?

- [x ] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

{{RANDOM}} return 41 always

**Comment by dannagle** [comment]
It looks like the first reply is 41, but then it will send random. Bizarre. I must not be seeding the random number generator until that first packet is send. Should be simple to fix.

**Comment by dannagle** [comment]
Fixed in development branch.
