### ISSUE TITLE
Socket Timeout Value?

### ISSUE THREAD

**Issue by ikshwa** [dannagle/PacketSender#160]
#### What OS?
- [ ] Windows 10

#### Description of issue
Can you please tell how the TCP socket parameter/ timeout and retry logic, if possible?
Currently , I am working on a software which connects with server  and send some strings. But it get hangs up when device is sleeping except I send with packet sender. Thus I am eager to see what exactly I am missing to make connection that packet sender doing.
Any help would be appreciated.
Thanks 
{{replace this}}

**Comment by dannagle** [comment]
Packet Sender has special logic to continue reading as long as the device continues to send data. There are also various settings Packet Sender supports such as delay-before-send, and delay-before-read. Embedded devices can be very slow to respond once connected. My advice is to place random delays between each step and keep reading until you get something.

The bulk of Packet Sender's TCP logic is inside tcpthread.ccp
https://github.com/dannagle/PacketSender/blob/master/src/tcpthread.cpp
