### ISSUE TITLE
Does PacketSender support 32bit OS

### ISSUE THREAD

**Issue by lazna** [dannagle/PacketSender#162]
Trying to start PS portable it on Windows 7 32bit, got following message:

This version of C:\PS\PacketSender.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.

what am I doing wrong?

**Comment by dannagle** [comment]
This was the last version that supported 32-bit:
https://github.com/dannagle/PacketSender/releases/tag/v5.7.52 

Perhaps it has enough features for you.

**Comment by lazna** [comment]
Thanks, it would be nice if there will be notice (and possilbly link to last32bit release) about stopped 32releasing on the download web page. I spent amount of time searchich for such info yesterday... 

thanks

**Comment by lazna** [comment]
Just trying the version you sent me but got following error:

Procedure entry point _ZN12QSystemError6stringENS_10ErrorScopeEi could not be located in the dynamic link library Qt5Core.dll

What am i doung wrong? Using portable version, just unzipped into the specific directory and started by command:

packetsender -uw 5000 255.255.255.255 10001 "01 00 00 00"

**Comment by dannagle** [comment]
Some ideas to try:

- Make sure the GUI works. 
- Directly call the .com version: "packetsender.com --version".  
- Try using the installer? I changed build procedures with that version. 
- Go back further back in time? You can try to find the oldest portable. I have installers pre-GitHub that go back to Windows XP I can send you. I don't remember how complete their command line support is though.   

I can verify that particular portable version I linked was compiled for 32-bit:
![image](https://user-images.githubusercontent.com/1140573/65806205-18b93380-e14e-11e9-989c-fbe45c518460.png)

A while back, I did receive confirmation from somebody else running Win7 32-bit for that particular version. I think they used installer + GUI. I don't know if they did any compatibility settings trickery or ran the command line. 

Hope that helps.

**Comment by lazna** [comment]
Vesrion 5.6.2 seems working on W7/32bit. Please do note it on web site to avoid the other people wasting time. Thanks a lot, L.

**Comment by lazna** [comment]
One question: If multiple On-link interfaces are present with same metric and packet destination is a broadcast (255.255.255.255), to which interface will be packet send?

**Comment by dannagle** [comment]
Indeterminate. An interface is chosen at random. This problem is why latest Packet Sender now supports binding to a particular address. [See issue number 148](https://github.com/dannagle/PacketSender/issues/148) . 

IP-binding forces the broadcast packet out a particular interface.

**Comment by lazna** [comment]
As far as i understand it now, 32bit version not support (and will not) this, right?

**Comment by dannagle** [comment]
Not unless you or someone else is willing to sponsor a one-off build and repackaging. WinXP 32-bit is out of the question, but I think tools for Win7 32-bit can still be resurrected.

**Comment by lazna** [comment]
What is the price?

**Comment by dannagle** [comment]
Please send me an email to discuss off GitHub: https://packetsender.com/contact

I'll research what it will take.

**Comment by dannagle** [comment]
For those stumbling upon this thread, a 32-bit version built for Windows 7 is now here: https://github.com/dannagle/PacketSender/releases/tag/v6.2.6
