### ISSUE TITLE
ASCII § / HEX A7 doesn't seem to encapsulate/transmit properly

### ISSUE THREAD

**Issue by nickolasjensen** [dannagle/PacketSender#166]
![Screen Shot 2019-11-14 at 4 15 27 PM](https://user-images.githubusercontent.com/48843696/68906689-01340b00-06fa-11ea-9d36-930d8eb21c10.png)
#### What OS?

- [ ] Windows
- [X ] Mac v6.2.3
- [ ] Linux (Which distro?)

#### Description of issue

{{ASCII § / HEX A7 doesn't seem to encapsulate/transmit properly}}

**Comment by dannagle** [comment]
I can't seem to recreate this. Am I doing the same thing as you? 

Mac Screenshot...
<img width="563" alt="mac screenshot a7 sequence" src="https://user-images.githubusercontent.com/1140573/68910146-744b7a80-0716-11ea-8e2c-6e0380e37d86.png">

**Comment by nickolasjensen** [comment]
The double S or [ in ascii, the actual character, doesn’t seem to translate. I can sent it from terminal echo and it works. I can dig in more tomorrow am. 


Sent from my iPhone


> On Nov 14, 2019, at 17:40, Dan Nagle <notifications@github.com> wrote:
> 

﻿
I can't seem to recreate this. Am I doing the same thing as you?

Mac Screenshot...

**Comment by dannagle** [comment]
I looked it up. The code is A7, which seems to work for me.
**Unicode: U+00A7 § SECTION SIGN**

The § symbol is not a traditional ASCII character (anything above 0x7F would fall under UTF-8), which is why it appears as \a7 in that ASCII text box. 

I've been on the fence of upgrading the entirety of Packet Sender to UTF-8 as potential breakage of existing installations is something that worries me. However, moving UTF-8 seems like a safe fix with more positives than problems. A fix like that would help this problem.

**Comment by nkod3288** [comment]
Hi

similar to the A7 transmission issue, I am trying to send non printable characters RS (Record Separator) and FS (File Separator) within my input (GUI) 
![RS](https://user-images.githubusercontent.com/72945453/96210493-0d46cf00-0f40-11eb-8ff5-624cd3a5d4ef.jpg)
and I see that prior to sending the request, its getting parsed as \1C AND \1E. and these aren't being accepted by the recipient server. May I know if there is any other work around.

I do see a -A / --ASCII within the command line utility however I couldn't make it work either

I see from your comment about UTF-8 upgrade. May I know if thats already been done or in progress. if so how sooon can we expect it to be available

**Comment by dannagle** [comment]
There is a load file button you can try on the far right. Use a separate editor to create your data and then load the file when done:

![image](https://user-images.githubusercontent.com/1140573/96254678-4e100980-0f7b-11eb-8f5f-6bb477f6b94a.png)

**Comment by nkod3288** [comment]
Thank you very much for quick turnaround...issue seems to be with my input file that was identified through wire shark

Regards
Rekha
