### ISSUE TITLE
TCP connection problem

### ISSUE THREAD

**Issue by Maxine3218** [dannagle/PacketSender#168]
#### What OS?

- [X] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

Under IPv4 Mode, every time I try to send a tcp package or build a persistent TCP connection, it says 'Could not connect'(persistent ot not). It can send & receive UDP messages successfully, and can receive TCP packages from an IOS version (non-persistent).

**Comment by Maxine3218** [comment]
UPDATE: I run this same program on another PC, and it works succesfully. I could receive TCP packages sent from it & could receive a persistent TCP request. I'm thinking that there might be something wrong with my firewall settings(maybe?), but I still don't know how to fix it.

**Comment by dannagle** [comment]
One firewall tweak is to just open that port entirely (set Packet Sender to listen on the port of your choice). Also, I have seen oddities if you have more than one NIC installed. Packet Sender gets confused and does not know which NIC to listen on. For that, you can directly bind the IP address you want to use to fix that problem. 

I am glad you managed to get a successful test to help you investigate.

**Comment by anastasiagubina** [comment]
I have this problem on Mac too. It makes me crying...........
