### ISSUE TITLE
Switched Import/Export Database icons

### ISSUE THREAD

**Issue by TheCrypt0** [dannagle/PacketSender#169]
#### What OS?

- [x] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

Thank you for the great piece of software! I've been using it almost every day since I downloaded it and has helped me a lot while reverse engineering communication protocols.

This is not really an issue but more of a "icon typo". As you can see from the screenshot below the icons regarding the Import/Export Database are switched. Is this a mistake or is it intended to be this way? 

![PacketSender_2020-01-14_17-07-59](https://user-images.githubusercontent.com/45895254/72360630-7c14a480-36f0-11ea-91a2-e0ffb5453ffe.png)

Cheers

**Comment by dannagle** [comment]
Well, how about that. I never noticed. I'll fix it next version. Good eye.

**Comment by dannagle** [comment]
Boom!

![image](https://user-images.githubusercontent.com/1140573/72366446-e2350380-36bf-11ea-8fb0-0f8486789de7.png)

**Comment by TheCrypt0** [comment]
Great! Thank you! :)

Closing.
