### ISSUE TITLE
how to use centos packetsender start tcp server?

### ISSUE THREAD

**Issue by ccwxl** [dannagle/PacketSender#170]
#### What OS?

- [x] Windows
- [ ] Mac
- [ ok] Linux (Which distro?)

#### Description of issue
```
Packet Sender is a Network UDP/TCP/SSL Test Utility by NagleCode
See https://PacketSender.com/ for more information.

Options:
  -h, --help         Displays this help.
  -v, --version      Displays version information.
  -q, --quiet        Quiet mode. Only output received data.
  -x, --hex          Parse data-to-send as hex (default).
  -a, --ascii        Parse data-to-send as mixed-ascii (like the GUI).
  -A, --ASCII        Parse data-to-send as pure ascii (no \xx translation).
  -w, --wait <ms>    Wait up to <milliseconds> for a response after sending.
                     Zero means do not wait (Default).
  -f, --file <path>  Send contents of specified path. Max 10 MiB for UDP, 100
                     MiB for TCP/SSL.
  -b, --bind <port>  Bind port. Default is 0 (dynamic).
  -t, --tcp          Send TCP (default).
  -s, --ssl          Send SSL and ignore errors.
  -S, --SSL          Send SSL and stop for errors.
  -u, --udp          Send UDP.
  -n, --name <name>  Send previously saved packet named <name>. Other options
                     overrides saved packet parameters.

Arguments:
  address            Destination address. Optional for saved packet.
  port               Destination port. Optional for saved packet.
  data               Data to send. Optional for saved packet.
```

start a tcp server using pacletsender command cli ?

**Comment by dannagle** [comment]
Packet Sender CLI does not support starting a TCP server on the command line. Only the GUI has it. This feature has been requested several times.

**Comment by sreedhartk** [comment]
> Packet Sender CLI does not support starting a TCP server on the command line. Only the GUI has it. This feature has been requested several times.

Hello Dan, is there a plan to bring this feature (starting TCP server) any time in Packet Sender CLI?
Btw, thanks a lot for this amazing tool!

**Comment by dannagle** [comment]
It is on the roadmap, but without a sponsor, it is not a high priority. That is why this request has lingered for so long. 

Comments like yours and hitting upvotes does help bring attention to the most wanted bug fixes and features. Getting accurate feedback to adjust priorities is difficult on this project because the app intentionally has zero tracking and zero analytics.

**Comment by dannagle** [comment]
This feature is now in the development branch

**Comment by dannagle** [comment]
This feature is now released.
