### ISSUE TITLE
Increase bandwidth of traffic generator on Ubuntu

### ISSUE THREAD

**Issue by rasmart9307** [dannagle/PacketSender#171]
#### What OS?

- [ ] Windows
- [ ] Mac
- [X] Linux (Which distro?) Ubuntu 19.0.4

#### Description of issue

i tried to use intense traffic generator however it only limited to 1mb to my client device, how to increase the bandwidt output?

**Comment by dannagle** [comment]
Hello, set the resend delay to 0 to have it run as fast as possible. 

If you are comfortable editing source code, you could edit it to remove UI refreshing and collecting metrics. This will allow it to send as fast as possible. The bandwidth measuring Packet Sender uses is a bit crude.

**Comment by dannagle** [comment]
There are now more options in the CLI version.
