### ISSUE TITLE
unable to send packet

### ISSUE THREAD

**Issue by aztech1234** [dannagle/PacketSender#172]
#### What OS?

- [ ..] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

hi, 

i'm trying to send a simple packet for testing but it seems like the packet couldn’t be sent out. 
![image](https://user-images.githubusercontent.com/56329510/73423135-31d52980-4366-11ea-92d9-71e7e31e88d3.png)

just to double check the address is the computer's IP add right, then what about the port? 

i have also set the basic response but there is no response whenever i sent the data.
![image](https://user-images.githubusercontent.com/56329510/73423222-7cef3c80-4366-11ea-85d9-e2677f5166d4.png)

is my settings wrong or am i missing out something?
any help will be appreciated. thank you.

**Comment by dannagle** [comment]
The traffic log shows that the packet was sent out. UDP is connectionless. You won't see a responses unless something was on the other side to catch the packet and send a reply. You can set up another Packet Sender to do this. You can also use a loopback test to check on the same computer. See this screenshot. It shows TCP, but the test works with UDP too. 
![packetsenderloopbacktesttcp](https://user-images.githubusercontent.com/1140573/73455423-06d6df80-433e-11ea-95c0-6d2bddc79cc0.png)
