### ISSUE TITLE
Tiny fonts

### ISSUE THREAD

**Issue by sirxyzzy** [dannagle/PacketSender#174]
#### What OS?

- [ ] Windows

#### Description of issue

Font size seems really small, see screenshot, I suspect this is because I am using a high DPI device (Surface Laptop 2) 2256x1504

<img width="529" alt="packetsender-fonts" src="https://user-images.githubusercontent.com/7274181/76151614-f45e6d00-6084-11ea-94b7-2261f0c0cbcd.png">

Most native apps work well, but I have seen this sort of thing before from Qt based apps. I couldn't find a way to adjust font sizes manually

As a reference, here is a screenshot of the default font size in notepad, on the same screen.

<img width="260" alt="notepad-fonts" src="https://user-images.githubusercontent.com/7274181/76151664-58813100-6085-11ea-8f44-d216d4f4fb01.png">

**Comment by dannagle** [comment]
I unfortunately do not own a Windows laptop with a retina display to test on. 

I know Qt has put effort in to this. It took them a while to look decent on retina Macbooks, but they did eventually get there. Perhaps their latest Windows kit has made progress. If I made a portable alpha with it, will you give it a quick launch on your laptop?

**Comment by sirxyzzy** [comment]
Sure, I would be happy to test it out. FWIW, I see similar behavior in QtBittorrent, it seems to afflict custom text, but standard widgets (somehow) scale text better.

There is some interesting discussion here, https://doc.qt.io/qt-5/highdpi.html

I may be able to do a local build and fiddle with things a bit myself, depending on how difficult it is to build on Windows

**Comment by dannagle** [comment]
Here is an alpha of my standard build using updated Qt libraries:
https://github.com/dannagle/PacketSender/releases/tag/v6.3.0-alpha

**Comment by sirxyzzy** [comment]
Looks the same as before, here is a screenshot...

<img width="460" alt="packetsenderalpha" src="https://user-images.githubusercontent.com/7274181/76274699-bb2a2680-6257-11ea-8d68-90d3e67170e4.png">

Let's see if I can build, then I can fiddle around...

**Comment by sirxyzzy** [comment]
I was able to build, but I don't really know Qt, but as I have never used Qt before I'm not making headway (and Qt is a monster) I tried something as simple as editing a UI file in an attempt to explicitly set a font and I got precisely nowhere. I tried setting some promising looking env vars:

QT_AUTO_SCREEN_SCALE_FACTOR    1
QT_ENABLE_HIGHDPI_SCALING      1

No joy there either.

Amusingly the Qt installer itself has the exact same "miniature font" behavior.

Hey, I tried!

**Comment by dannagle** [comment]
Qt does a mix of its own widget rendering and native rendering. Something got lost in translation. If the Qt installer itself does it, the bug may be baked pretty deep and outside my control. I'll probably have to wait for them to fix. I appreciate your effort!

**Comment by dannagle** [comment]
This issue is basically the same problem mentioned here: #297 .  Closing this one (yes, I know this one was opened first).  Some fixes have been put place. More is needed.
