### ISSUE TITLE
packet sender v6.2.3 udp not working (vs v6.1.25)

### ISSUE THREAD

**Issue by shokata152** [dannagle/PacketSender#175]
#### What OS?

- [X ] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

We have used packet sender for a lot of time and it is great for us. 
We have used v6.1.25 and everything worked fine. 

two days ago we installed v6.2.3.

we have tested it vs our simple self test code on GoLang:

package main

import (
	"fmt"
	"net"
)

func main() {
	ServerConn, _ := net.ListenUDP("udp", &net.UDPAddr{IP: []byte{0, 0, 0, 0}, Port: 1337, Zone: ""})
	defer ServerConn.Close()
	buf := make([]byte, 1024)
	for {
		n, addr, _ := ServerConn.ReadFromUDP(buf)
		fmt.Println("Received ", string(buf[0:n]), " from ", addr)
	}
}

This code worked perfectly vs v6.1.25. It didn't work vs v6.2.3.
To verify we reinstalled v6.1.25 and the code works again. 

Currently we rolled back to v6.1.25 and everything works. 

thank you for this great program =]

**Comment by dannagle** [comment]
I've not used Golang. A new feature in v6.2.3 is IP-specific binding. This is needed to support computers with multiple NICs. Have you tried binding the IP in settings? If v6.1.25 is working fine feel free to stick with it.

**Comment by magdesign** [comment]
Linux Ubuntu 18.04

Packetsender 6.x does not send any UDP messages at all, **UDP function is broken**.

Testet with ` tcpdump -u`, 
please fix or at least mention it in the download section. I wasted 6h hours in debugging why my scripts did not work to come to the point that the testing tool (packetsender) is not working.

**Comment by dannagle** [comment]
- Is this command line or GUI?

- Does it work if you bind to your IP address in settings?

![image](https://user-images.githubusercontent.com/1140573/87213130-3f64e700-c2e8-11ea-9f8a-19562b939a73.png)

**Comment by dannagle** [comment]
Also, there are currently beta releases available. I am curious if you are still having this problem using them:
https://github.com/dannagle/PacketSender/releases

**Comment by magdesign** [comment]
- The beta-releases do not contain any Linux build.
- Tested with PacketSender_Linux_x64_v6.2.3.AppImage and Snap, both do not send UDP.
- It works nice with older version: 5.7.52

Yes, binding my own IP in the settings helps, when doing so UDP messages are sent (tested with tcpdump)!

**Comment by dannagle** [comment]
If you cycle binding a couple times (by clicking the bottom right button) to where it says "IPv6" and then back to "IPv4", does it keep working?

**Comment by dannagle** [comment]
There is a new beta AppImage in releases. Tested with Ubuntu 18 and 20 LTS.

**Comment by magdesign** [comment]
@dannagle : Thank you very much for fixing, build 7.0.4 works as expected!
