### ISSUE TITLE
CPPFLAGS missing (-D_FORTIFY_SOURCE=2)

### ISSUE THREAD

**Issue by eribertomota** [dannagle/PacketSender#180]
#### What OS?

- [ ] Windows
- [ ] Mac
- [x] Linux (Debian)

#### Description of issue

When packaging, Debian applies all possible hardening flags for GCC/G++. A specific line is not receiving -D_FORTIFY_SOURCE=2 (all other lines has this flag). The `blhc --all --debian` command shows:

`
CPPFLAGS missing (-D_FORTIFY_SOURCE=2): /usr/bin/c++ -dM -E -c /usr/share/cmake-3.16/Modules/CMakeCXXCompilerABI.cpp -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/PKGS/packetsender/packetsender/obj-x86_64-linux-gnu -I/PKGS/packetsender/packetsender/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include
`

See below two right lines as an example:

```
[ 80%] Building CXX object CMakeFiles/PacketSender.dir/packetnetwork.cpp.o
/usr/bin/c++  -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/PKGS/packetsender/packetsender/obj-x86_64-linux-gnu -I/PKGS/packetsender/packetsender/src -I/PKGS/packetsender/packetsender/obj-x86_64-linux-gnu/PacketSender_autogen/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets  -g -O2 -fdebug-prefix-map=/PKGS/packetsender/packetsender=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -fPIC -o CMakeFiles/PacketSender.dir/packetnetwork.cpp.o -c /PKGS/packetsender/packetsender/src/packetnetwork.cpp
[ 83%] Building CXX object CMakeFiles/PacketSender.dir/persistentconnection.cpp.o
/usr/bin/c++  -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/PKGS/packetsender/packetsender/obj-x86_64-linux-gnu -I/PKGS/packetsender/packetsender/src -I/PKGS/packetsender/packetsender/obj-x86_64-linux-gnu/PacketSender_autogen/include -isystem /usr/include/x86_64-linux-gnu/qt5 -isystem /usr/include/x86_64-linux-gnu/qt5/QtCore -isystem /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -isystem /usr/include/x86_64-linux-gnu/qt5/QtGui -isystem /usr/include/x86_64-linux-gnu/qt5/QtNetwork -isystem /usr/include/x86_64-linux-gnu/qt5/QtWidgets  -g -O2 -fdebug-prefix-map=/PKGS/packetsender/packetsender=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2   -fPIC -o CMakeFiles/PacketSender.dir/persistentconnection.cpp.o -c /PKGS/packetsender/packetsender/src/persistentconnection.cpp
```

Looking the problematic line, I can't see an object or executable being created. Looking around the line, I can see:

```
AutoGen: Refreshing parse cache because it doesn't exist.
AutoMoc: Generating "BIN:/PacketSender_autogen/moc_predefs.h", because it doesn't exist.
/usr/bin/c++ -dM -E -c /usr/share/cmake-3.16/Modules/CMakeCXXCompilerABI.cpp -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -I/PKGS/packetsender/packetsender/obj-x86_64-linux-gnu -I/PKGS/packetsender/packetsender/src -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include
```

Thanks!

**Comment by dannagle** [comment]
qmake is now passing that flag for linux.

**Comment by eribertomota** [comment]
Not working here. The line `CPPFLAGS missing (-D_FORTIFY_SOURCE=2):` is present yet.

**Comment by dannagle** [comment]
How are you compiling? Do you have a link to the build script?

The method I expected is:
` qmake PacketSender.pro && make `

This should generate a lowercase "packetsender" (as specified by [in the .pro file](https://github.com/dannagle/PacketSender/blob/aa5a08aad0cbd120c4e1b234b1a29943d3e5f8db/src/PacketSender.pro#L9) )  . Your suggestions in #181 seems you are getting camel-case. 

Perhaps I can have this project work better with different build systems.

**Comment by eribertomota** [comment]
Hummm... I used default build system from Debian. You can see here[1]. However, I can change the build method manually.

[1] https://salsa.debian.org/debian/packetsender/-/blob/debian/master/debian/rules

I attached a build log. Please, tell me if I need change the build method. Note that the Debian build system follows the way pointing by some upstream files (as configure.ac, configure, etc). So, I can see an initial build using cmake.

[packetsender_6.2.6-1_amd64.build.zip](https://github.com/dannagle/PacketSender/files/4549633/packetsender_6.2.6-1_amd64.build.zip)

**Comment by dannagle** [comment]
I will dig in to this when I have more time. I want to follow best practices. I changed the Packet Sender executable to lowercase all platforms as of a year ago. If there is a place I missed I'd like to fix it.

**Comment by eribertomota** [comment]
I am closing this issue because the line produced by blhc is a false positive. This line is a check for compiler flags and the resulting objects never end up in any artifacts from the build. This action is recurrent in CMake. In this case, I can ask for the blhc to ignore this line via debian/rules.

Reference: https://gitlab.kitware.com/cmake/cmake/-/issues/20631#note_746828

**Comment by bigbigmdm** [comment]
I added this line to `debian/rules` in version 1.3.9, but it didn't help.
