### ISSUE TITLE
packet sender

### ISSUE THREAD

**Issue by sandeep773** [dannagle/PacketSender#182]
#### What OS?

- [x] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

how i can send 500 packets to host

**Comment by sandeep773** [comment]
how i can send 500 packets to host

**Comment by dannagle** [comment]
Go to File -> Settings

There is a field that lets you cancel after sending X packets.
![image](https://user-images.githubusercontent.com/1140573/81060964-1d3e8b00-8e99-11ea-95c8-1a42e92aac4f.png)

Then on the main Packet Sender screen, choose a resend delay.
![image](https://user-images.githubusercontent.com/1140573/81060988-2c253d80-8e99-11ea-8660-3e3cc5949d05.png)

Packet Sender will resend the packet X times at that rate. Note that the rate is a best effort calculation.

**Comment by sandeep773** [comment]
I am facing issue in sending packet to signup page can you help me out over
phone call or by screen share.

**Comment by dannagle** [comment]
Closing as this was answered over email ( the answer was to use the Cancel Re-sending feature in settings UI)
