### ISSUE TITLE
Incomplete TCP packets

### ISSUE THREAD

**Issue by emert117** [dannagle/PacketSender#183]
#### What OS?

- [ x] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue
I get incomplete TCP packets. 

I must see 0x1C byte at the end of TCP packets. But I can't see this byte.

Is there a buffer size limitation?

**Comment by dannagle** [comment]
Each line in the Packet Sender log can display roughly 16 kilobytes.
