### ISSUE TITLE
packetsender with cable box

### ISSUE THREAD

**Issue by anothertckt** [dannagle/PacketSender#186]
#### What OS?

- [x] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

**Comment by anothertckt** [comment]
Hello Support,
I'm trying to use packetsender command line interface to send a learned code [INFO} to a cable box via  Global CacheiTach It appears to run although nothing appears graphically on the video. It works using the GUI although it doesn't using a CLI or batch file. The command line is:  packetsender -t 10.100.7.17 4998 "sendir,1:3,1,58000,1,1,192,192,48,144,48,144,48,48,48,144,48,144,48,48,48,48,48,48,48,144,48,48,48,48,48,48,48,48,48,144,48,48,48,48,48,144,48,144,48,144,48,48,48,144,48,144,48,2534". Screenshot attached:
Clearly I'm missing something...

![packetsnd_cli](https://user-images.githubusercontent.com/68246575/87341269-589faa80-c517-11ea-9bff-ba2787cb5eea.jpg)

Thanks,
Anothertckt

**Comment by dannagle** [comment]
Try adding a 1 second wait command `-w 1000` 

It may be quitting too quick on you.

**Comment by anothertckt** [comment]
Thanks for the prompt response. I’ll give it a whirl once my head squares. Been going a few good rounds with this thing. It’s peculiar since another office using the same setup (packet sender>Global Cache) although their using a different cable provider./box.

Thanks,

Ken

**Comment by anothertckt** [comment]
Hello Dan,
Inserted a wait of 3000 and now getitng responses from the device although the  last line displays an error (016\r) which appears to be some sort of carriage return issue. I tired adding \r but still getting the same result. Unless there's a syntax issue.
![err016](https://user-images.githubusercontent.com/68246575/87567254-12bb2180-c692-11ea-9819-ebb18cbc457c.jpg)

Thanks,
Ken

**Comment by dannagle** [comment]
try adding "`-a`" to state you are using mixed-ascii notation.

**Comment by anothertckt** [comment]
I tried the -A and the lower case -a
![err16_2](https://user-images.githubusercontent.com/68246575/87576069-d5a95c00-c69e-11ea-9225-b582c9a2a0fa.jpg)
Thanks,
Ken

**Comment by dannagle** [comment]
At a glance, it looks like you are now sending the full ASCII. 

Another idea... if it working in the GUI, you can tell the command line to send that named packet with the "`-n`" notation where you state the name of the saved packet.

`packetsender -n "mysavedpacket" -w 3000 127.0.0.1 5000
`

**Comment by anothertckt** [comment]
yes, i use the gui, it opens a 2nd window, pasted the code in the ascii field using persistent tcp, and voila, it works. I close that 2nd window then save the named packet, "test1". Where does it save the packet/file? It doesn't appear to be listed in the packet sender folder.

**Comment by dannagle** [comment]
the CLIi queries the packet sender database to send.  if you saved it in the GUI then the command line can find it using `-n` option.

**Comment by dannagle** [comment]
About your initial question... It stores packet data in `C:\Users\_username_\AppData\Local\PacketSender`. You can override this using portable mode: https://github.com/dannagle/PacketSender#portable-mode

**Comment by dannagle** [comment]
if you called it `test1`, your command line would like...
```
packetsender -n "test1" -w 3000 10.100.7.17 4998
```

**Comment by anothertckt** [comment]
yes, figured the app did that: find the packet/file. There's a file in that folder called packets.ini. I tried the test1 in the command line but it says not found. Odd.
![testpck_notfound](https://user-images.githubusercontent.com/68246575/87594427-ecf64280-c6ba-11ea-8a71-cb2628d80e72.jpg)
does a packet.ini file need to be in the same folder as packetsender? I'm runing the portable ver. on this pc. i renamed the folder from packetsender_port > packetsender.

**Comment by dannagle** [comment]
It is case-sensitive. Did you call it "`test1`" (lowercase) ?

Yes, `packets.ini` needs to be in the same folder. Otherwise, it will look for it in your local `%appdata%`. You can open up `packets.ini` in an editor and see the names.

**Comment by anothertckt** [comment]
Copied packets.ini to the packetsender folder. It's listed as TEST1. Seems like it's on the cusp of working. The ascii 016 error keeprs rearing it's head. If use the devices app, itest., it includes a checkbox for using a carriage return if it means anything re: the error.
Thanks for your
![testpck_er16](https://user-images.githubusercontent.com/68246575/87596569-575cb200-c6be-11ea-9bfc-50d766625091.jpg)
 patience and diligence.

**Comment by dannagle** [comment]
you don't need the `-a` if you send from a saved packet.

**Comment by dannagle** [comment]
If you need the carriage return at the end, you will need to append the `\r` in the saved packet. Perhaps name it something else to not mess up TEST1 that you got working.

**Comment by anothertckt** [comment]
i'm saving the packet with the append \r checked. It needs to be added to the packets.ini?
![appendcr](https://user-images.githubusercontent.com/68246575/87853575-49cf4400-c8d9-11ea-8f2c-53849a27af95.jpg)

**Comment by dannagle** [comment]
If you want the carriage return sent, then yes.  Add a `0d` to the end. 

The purpose of the "\r" in the persistent TCP window is so it can easily emulate a telnet session --hitting enter will also send a carriage return.

**Comment by anothertckt** [comment]
Bingo! That did it. The pesky carriage return. Thank you sir for your prompt, thorough responses, patience, and diligence. Cheers!
