### ISSUE TITLE
Persistent TCP on the server side [enhancement]

### ISSUE THREAD

**Issue by svetlin** [dannagle/PacketSender#19]
Currently PacketSender seems to close the connection from a client (which has opened a persistent TCP connection) as soon as the first message from the client has been received and responded to. Here is a log from my custom client:
[Client] Successfully wrote message Hello Server
[Client] Received Message Hello from PacketSender
[Client] Successfully wrote message some_message
(some_message is not received by PacketSender)
[Client] Successfully end connection received
[Client] Successfully closed connection

(The "Hello from PacketSender" is the response configured using the GUI on PacketSender)

It would be helpful if PacketSender can maintain a persistent TCP connection on the server side and wait for the client to close it. And maybe have a GUI button "Close All Connections" for the TCP port.

**Comment by dannagle** [comment]
You are correct. Packet Sender's built-in TCP server closes the connection after a few seconds. Persistent connections is currently only supported using Packet Sender as a client.

**Comment by svetlin** [comment]
Thanks for the quick reply. 
Any chance of enhancing the server to maintain a persistent TCP connection? 
If not, any pointer to which standalone TCP server for Linux does that (I could not find any)?

**Comment by dannagle** [comment]
I do not know of any. 

What is your timeline? It's been on my to-do for a while. I could make a special branch if you don't mind an ugly UI. The problem I couldn't nicely solve was a rogue device making a bunch of connections which caused a bunch of connections pop-ups. I then shelved the idea because I ran out of time. After all, this is an unpaid volunteer effort by me.

**Comment by svetlin** [comment]
I found this one
http://sockettest.sourceforge.net/
https://github.com/akshath/SocketTest
which is written in Java, hence cross-platform. It maintains a persistent connection, but cannot be configured to respond automatically (only manually) and does not seem to have been updated in a while.

I don't mind if the server does not have any UI, let alone an ugly one. For me, personally, more important is performance because I'll be using it for testing from a Java NIO client which is capable of quickly sending many messages using the same socket. Also, valuable to me is the ability to configure an automatic response from the server, e.g. echoing back the last received message.

As for a timeline, I don't dare to request anything. If and when you have the time. This server might be useful for development and testing in a home network automation/entertainment environment where a mobile client controls remote devices over sockets in near real-time, among other scenarios.

Thank you for your effort, appreciated.

**Comment by dannagle** [comment]
If you are still looking for this feature, I made a pre-release version here: https://github.com/dannagle/PacketSender/releases/tag/v5.0-alpha

It will eventually get formally released for all platforms.

**Comment by dannagle** [comment]
this is now fully released.

**Comment by svetlin** [comment]
Tested to maintain a permanent connection by default. Don't see a way to turn this off/on, but not needed for my purposes. Thanks!

**Comment by jpt60** [comment]
Hi Dan,
Can you please let me know whether PacketSender closes the UDP connection after sending the response?
I am developing a client prototype, UDP, connection oriented, with a blocking recv call, but it never recieves the reply that is sent by PacketSender (and which is visible on Wireshark).
Could it be that PacketSender has closed the connection gracefully, so that recv is returning 0?

Many thanks for your assistance and insights.

**Comment by dannagle** [comment]
UDP is connectionless. There is not a connection to close. Packet Sender's UDP socket is always listening. You can turn on responses on 2 Packet Senders, and they will happily UDP reply back and forth to each other until the app dies from using too much RAM. Turn off logging to have it go on forever.

If you are referring to TCP, Packet Sender replies back once and closes the connection. Turn on persistent TCP, and then Packet Sender will reply and leave the connection open. It still only replies once. Replies with persistent TCP enabled is a bit buggy.

**Comment by jpt60** [comment]
Hi Dan,

 

Thanks for the explanations, very helpful for me to learn how UDP works. 

 

In the meantime, I found my code had an error preventing the correct filling/reading of the client buffer when recv().

 

So all is good  now. Many thanks!

**Comment by duwi2mex** [comment]
Mmmh. In V5.6.2 it seems to be closing the TCP socket connection after every command again. Can you confirm?
Thanks!

**Comment by dannagle** [comment]
- Client (outgoing) or server (incoming) connections? 
- Are you using installed or portable?

I've not seen this problem. However, Qt did change their socket libraries on me again. I had to do a fair bit of rework.

**Comment by duwi2mex** [comment]
Server and portable. Sorry.

**Comment by duwi2mex** [comment]
Hi Dan,

I tried with persistent TCP enabled but it did not change anything related to the mentioned behavior. Do a have to use it to keep the connection open?

I send commands by another computer and each command starts with STX and ends with ETX, e.g. 
\02_AKON K0\03
Then I use the smart replies inside your tool. The first command after opening the socket connection receives the correct response. 
The 2nd command however, finds a closed socket connection. At least that’s what I think it is. Our tool then reopens the connections after reaching a timeout. 

Thanks and best regards,
Lars

**Comment by AndrejMueller01** [comment]
Same here.

> Hi Dan, I tried with persistent TCP enabled but it did not change anything related to the mentioned behavior. Do a have to use it to keep the connection open? I send commands by another computer and each command starts with STX and ends with ETX, e.g. \02_AKON K0\03 Then I use the smart replies inside your tool. The first command after opening the socket connection receives the correct response. The 2nd command however, finds a closed socket connection. At least that’s what I think it is. Our tool then reopens the connections after reaching a timeout. Thanks and best regards, Lars
> […](#)
> Am 17.04.2018 um 03:17 schrieb Dan Nagle ***@***.***>: I got a fresh copy. It's working for me. Is persistent TCP checkbox is checked? I used a Linux VM to telnet to portable Packet Sender's TCP server address. Sent data. Saw it appear. Then left it open a while. — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Souryadeep** [comment]
Hi, does the GUI only work on windows?

**Comment by dannagle** [comment]
All the features of Packet Sender runs on Windows, Mac, and Linux.
