### ISSUE TITLE
new version 7.0.5 can't use ssl

### ISSUE THREAD

**Issue by bitbegin** [dannagle/PacketSender#192]
#### What OS?

- [ x] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

![图片](https://user-images.githubusercontent.com/4469745/88893483-fe257e80-d278-11ea-8bb9-0c477316007b.png)

**Comment by dannagle** [comment]
Does the portable version work?

**Comment by bitbegin** [comment]
@dannagle  doesn't work either.

**Comment by dannagle** [comment]
It seems I upgraded OpenSSL but did not upgrade the bundled libraries. 

Does it work if you copy these extra files in to the install folder?
https://packetsender.com/ps_openssl_dlls.zip

**Comment by dannagle** [comment]
I just pushed a new installer and portable with the openssl fix.

**Comment by bitbegin** [comment]
@dannagle the file https://packetsender.com/ps_openssl_dlls.zip can fix this issue

**Comment by dannagle** [comment]
Thank you for bringing this problem to my attention. My test computer completely missed this since it had openssl from somewhere else. That's fixed too. 

The installers have been updated. Closing this ticket.
