### ISSUE TITLE
Add option to show full response

### ISSUE THREAD

**Issue by Phenomite** [dannagle/PacketSender#194]
#### What OS?

- [x] Windows
- [ ] Mac
- [x] Linux (debian aptitude)

#### Description of issue

Latest release `7.0.5` has appended `[...]` to both ASCII and Hex view for packet data that exceeds a certain size, and theres no option to show the full data.

This is most painful reading DNS responses where RRSIG nowadays cause bloated information, had to use wireshark to view the full thing!

**Comment by dannagle** [comment]
It seems that by solving one problem I caused another. 

You can use "Copy to Clipboard" to get the full data packet to then paste into an editor:
![image](https://user-images.githubusercontent.com/1140573/90011485-496f6200-dc67-11ea-982e-55a20a83de7d.png)

By default, it copies raw binary. If you need the ascii/hex translation, uncheck this box in settings:
![image](https://user-images.githubusercontent.com/1140573/90011571-70c62f00-dc67-11ea-8f08-f277e5287d42.png)

I hope that workaround is enough. I've flagged this ticket as a request so I can add a toggle to the next release. Not having one was an oversight on my part.

**Comment by dannagle** [comment]
![image](https://user-images.githubusercontent.com/1140573/90462359-5ad4c600-e0ce-11ea-9a21-09c10dda5831.png)


This change is now in the development branch. Closing this ticket.
