### ISSUE TITLE
Cannot receive UDP Broadcast packets?

### ISSUE THREAD

**Issue by capsicumDreams** [dannagle/PacketSender#201]
#### What OS?

Windows 7.0.6 (10 Sept 2019)

#### Description of issue

I can't seem to receive Broadcast 255.255.255.255 UDP packets.
I can on other apps on the same PC, so I think it's not a network issue.

Is this by design?

Fantastic app, btw.. :)

**Comment by dannagle** [comment]
You should be able to receive broadcast packets no prob. There is nothing in the design to prevent this.

Make sure you are listening to the port the packets are being sent on. Check the bottom right for the UDP port. Also, make sure you are in IPv4 mode. See screenshot.

![image](https://user-images.githubusercontent.com/1140573/97003931-da817580-1501-11eb-99f7-212eab6abc94.png)

It is **extremely common** for routers to filter broadcast packets. If you are still having problems, I recommend connecting your two computers directly bypassing everything in between. Then work your way outward to your normal setup. 

BTW, you can also run 2 packet senders at the same time if you bind everything to 0. This is typically done for localhost testing, but a broadcast test would work too.  See this screenshot. Make sure you have auto-responses turned off.

![image](https://user-images.githubusercontent.com/1140573/97004269-6dbaab00-1502-11eb-8c7a-3a388c50ca7e.png)


Hope this helps.

**Comment by capsicumDreams** [comment]
Thanks for the feedback. Much appreciated..

Some more context. I am sending these broadcast 255.255.255.255 UDP packets from an Android app on the WLAN to port 49002.
I can receive the packets from an old program "Internet Manic" v1.2d using the 'Port Listener' function.
![image](https://user-images.githubusercontent.com/2741536/97087693-28929800-162c-11eb-83ae-41dc7d8dec58.png)

So, I would have thought that it's not a network issue.

I'm using the latest Packet Sender v7.0.6, and have set the UDP server to 49002, but cannot receive those same packets. (Having closed the other app, obviously).
I have checked sending from one PS instance to the other as you suggested, and that works just fine. (I'm not sure what _Bind everything to 0_ means).

So, at this point, maybe it **is** a network issue, rather than a Packet Sender issue?
Are there two kinds of broadcast packets? 

I don't want to absorb your time if you can't see anything obviously wrong that I'm trying, or haven't tried..

But any ideas before I head to StackOverflow would be great! :)

**Comment by dannagle** [comment]
Do you have more than 1 network connected?

Rather than do a general bind, you can force Packet Sender to bind to the IP address you plan to use in settings. It may add some stability if you are having problems. 

![image](https://user-images.githubusercontent.com/1140573/97088251-38db5080-15f5-11eb-84ae-f63fb57a26ed.png)

**Comment by capsicumDreams** [comment]
There are a few interfaces, if I understand the titlebar correctly:
![image](https://user-images.githubusercontent.com/2741536/97088841-e4a39100-1633-11eb-9992-254b0104c7eb.png)

I bound to the regular IPv4 address 192.168.0.110 I get from ipconfig as you suggested, and still no data coming through..

**Comment by dannagle** [comment]
Without fully knowing your setup, here are some network troubleshooting tips I would attempt to track down the problem. Perhaps one of these will find it. 

- Check that a unicast (UDP send to 192.168.0.110, port 49002) works

- Go to your Network Settings and disable all network adapters (including virtual ones) except the exact one you care about. Broadcast may be going out the wrong adapter.

- Reboot (this makes sure a misbehaving app is not consuming ports)

- Remove extra IP addresses if using any (broadcast packet generation may be using the wrong source IP you want -- it _shouldn't_ matter, but might as well fix it)

- Run Wireshark and see if the packet is actually arriving. Inspect it to see the IP, method, and destination port is what you expect

- Use a single Ethernet cable to direct connect bypassing all routers, switches, etc. Then rerun the test. Then work your way backwards reconnecting the setup until it stops working.

- Check your arp cache

- Disable firewalls (if a LAN setup)

**Comment by capsicumDreams** [comment]
..still trying to figure this out..

**Comment by dannagle** [comment]
Are you able to broadcast locally within Packet Sender? Screenshot...

![image](https://user-images.githubusercontent.com/1140573/97578277-8f160e00-19be-11eb-8e23-1edc1130696a.png)

**Comment by capsicumDreams** [comment]
Yes, I can, from itself, and from another running PS on the same machine.

I've just testing running PS on another machine on the WLAN. It receives Brodcast and Unicast perfectly.
So the conclusion might have to be some weird interaction with "Internet Maniac", perhaps?

In any case, I can't fault PS at all, love using it and (apart from some awkward screen scaling issues on Win10) have no issues.
Thanks so much for your help - sorry I couldn't conclusively prove either way what was happening..
