### ISSUE TITLE
question file upload location

### ISSUE THREAD

**Issue by n1ck-unikat** [dannagle/PacketSender#203]
#### What OS?

- Windows 10

with the file option , i send with ssl a file to the server. Are the files really uploaded or only the hex codes? 
i want show if the files are curropted or function.

**Comment by dannagle** [comment]
Packet Sender reads the file as a series of raw bytes. That is what it sends. It is sending the contents of the file. The hex codes you see is the byte representation that it read and sent.

Hope that helps.

**Comment by n1ck-unikat** [comment]
Yes, thats its a help. But i have different data portion on tcp. With wireshark i see the full payload.
on udp the data portion is always the same. Means tcp file is currupted?

**Comment by dannagle** [comment]
Are you using the command tool or the GUI?

**Comment by n1ck-unikat** [comment]
i used the gui, but will try and check with cli again!
