### ISSUE TITLE
Do not include ps_settings.ini in the portable version

### ISSUE THREAD

**Issue by Sopor** [dannagle/PacketSender#204]
#### What OS?

- [x] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue
I'm running the portable version of Packetsender and I noticed that the file ps_settings.ini was included in the PacketSenderPortable_v7.0.6.zip. That isn't a very good idea to include that file because if I take the whole package and overwrite my existing files, I will lose my ps_settings.ini settings.

The file is 0 byte so it would be much better to not include the file and create the file when it is needed.

**Comment by dannagle** [comment]
The workflow I envisioned was the user copying their settings and data to the new portable. I did not think about users copying the other direction. I can see the need to support either. Thanks for the suggestion.

**Comment by dannagle** [comment]
Just giving you a quirk warning. A new release is coming soon. I think this is a great idea, but unfortunately, it did not make into this release. My plan is to get it into the following one.

Thanks again for the input.

**Comment by dannagle** [comment]
This is now fixed in the development branch. The magic file is called `portablemode.txt`.  If that exists, Packet Sender will run in portable mode and generate any needed files that are missing.
