### ISSUE TITLE
Connect/ close via TCP

### ISSUE THREAD

**Issue by bremenpl** [dannagle/PacketSender#205]
#### What OS?

- [ ] Windows

#### Description of issue

Hello there,
I was wondering whether it is possible to somehow only perform the following operation via TCP sockets:
- Connect,
- Close.

Currently, `Connect` is being sent out automatically with the first TCP packet. Is there a way to distinguish this command manually?

I would appreciate all help.

**Comment by dannagle** [comment]
You don't actually have to send data when you start a connection. 

You could try this. 

1. Enable "Persistent TCP"
![image](https://user-images.githubusercontent.com/1140573/98759333-7df1d780-2396-11eb-91b7-b873911e047f.png)

2. Leave the ASCII/HEX blank
![image](https://user-images.githubusercontent.com/1140573/98759350-89450300-2396-11eb-9ac4-03c99a9fcdba.png)

3. Click "Send" to start the TCP connection. There is no data being sent, so it is behaving like your "Connect" command.  A pop-up will appear that is holding the session. 

4. When done, hit "close" to close the connection. 

Repeat 3 and 4 as needed.
