### ISSUE TITLE
Incorrect message on port binding if both UDP and TCP servers enabled

### ISSUE THREAD

**Issue by bladerunner2020** [dannagle/PacketSender#206]
#### What OS?

- [ ] Windows
- [x ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

If you enabled both UDP and TCP server (with one port each) and TCP port is already bound with another app then PacketSender says that it cannot bind **UDP port** on start (it should complain about TCP port).

Though it opens UDP port and works as expected. So it's only about wrong message on PacketSender start.

**Comment by dannagle** [comment]
Confirmed. Bug in the pop-generation.

**Comment by dannagle** [comment]
Fixed in development branch.
