### ISSUE TITLE
Dark Mode!

### ISSUE THREAD

**Issue by carstengehling** [dannagle/PacketSender#207]
> Everybody loves dark mode, right? The entire UI was re-themed!

Erm... no, not everyone. ;-) An option to switch between new and previous theme would have been sweet.

**Comment by dannagle** [comment]
I agree! See #193 to follow.  

It's on the list for next release.

**Comment by carstengehling** [comment]
Cool! It's not really a game-changer, so I almost felt embarrased for bringing it up. Having authored a couple of OSS projects myself, I know how users can overflow you with issues, unaware that you might have other things to spend your time on. ;-)
