### ISSUE TITLE
Send packet simultaneously

### ISSUE THREAD

**Issue by frozen4sh** [dannagle/PacketSender#209]
#### What OS?

- [x] Windows
- [ ] Mac
- [ ] Linux (Which distro?)

#### Description of issue

Hi there,

Currently, I'm using Packet Sender for a test and I feel it's an awesome tool. 

I need to send UDP XML and UDP commands for 2 PC simultaneously by 2 each port.

For example, I will use Packet Sender on PC-A.

I will send UDP XML to PC-B by port 8888
I will send UDP command to PC-C by port 8889

By clicking 2 send button in Packet Sender, I could send for now.
But I need to find a solution that could be sent simultaneously.

Is there any way I could send those simultaneously?
Or is there any other tool could do?

Cheers,
Justin

**Comment by dannagle** [comment]
Hello,

I'm happy you like Packet Sender. A new feature that is in the development branch could do this. It is designed to cover your exact use case: Click a single button to trigger multiple packets --though it runs sequential, with UDP, that is very nearly simultaneous. The overall feature is not quite ready for a public release, but it is stable. 

I can get an early build to you if you would be willing to click around and test it a bit and send me your thoughts --both praise and constructive criticism. 

Please email me at hello@packetsender.com if you are interested. Thanks in advance.

**Comment by dannagle** [comment]
New panel generation feature is now published.
