### ISSUE TITLE
Installed by snap on Ubuntu, does not work

### ISSUE THREAD

**Issue by griffin-warrior** [dannagle/PacketSender#211]
#### What OS?

- [ ] Windows
- [ ] Mac
- [x] Linux Ubuntu 16.04

#### Description of issue
I just installed packet sender by snap. And it does not work, showing the following error message:
```
cannot create user data directory: /home/users/xxx/snap/packetsender/4: Permission denied
```

**Comment by dannagle** [comment]
Thanks for the heads up about this. 

It seems the snap is simply out-of-date and needs rebuilding. I can make a fresh snap for the Ubuntu stable branch soon and will ping this ticket when done.

**Comment by griffin-warrior** [comment]
@dannagle 
Thanks for your quick response. 
Today I also found it has the same error on Ubuntu 18.04 (snap version).
For PacketSender_v7.0.5.AppImage, it works on Ubuntu 18.04 and fails on Ubuntu 16.04, showing "Aborted."

**Comment by dannagle** [comment]
Thanks for checking those other versions. Looking at this... I don't think I can support 16.04 via AppImage. Far too many libraries require manual backporting and recompiling that I don't have time to do. 

I do need a new snap though, and Ubuntu now has a convenient pipeline to help speed that process.

**Comment by dannagle** [comment]
Snap support improved. Closing this.
