### ISSUE TITLE
no developer info?

### ISSUE THREAD

**Issue by polycopter** [dannagle/PacketSender#22]
I wish there were some kind of information provided about building on Windows (how to satisfy the Qt dependency, e.g.)... or did I miss that info somewhere?

**Comment by dannagle** [comment]
1. Download the Qt installer from http://www.qt.io/download-open-source/
1. Let it install MingGW if you don't have a compiler. 
1. Open the project PacketSender.pro
1. Build! Qt is the only dependency!

**Comment by polycopter** [comment]
brilliant! thanks.
