### ISSUE TITLE
UDP Server Ports are not saved in config (OSX El Capitan)

### ISSUE THREAD

**Issue by Terr4** [dannagle/PacketSender#24]
UDP Server Ports are not saved in the config on OSX El Capitan.

Steps to reproduce:
1. Open Packet Sender -> Preferences -> Network
2. Set UDP Server Port from default 55005 to 90 and enable UDP Server if not set
3. Save settings by pressing OK
4. Packet Sender shows "UDP Server Disabled" at the bottom
5. When going back to Preferences it shows Port 55005 again

**Comment by dannagle** [comment]
You closed this, so maybe you figured it out. For those that don't know, low port numbers (1024 and less) require admin / root permissions.

Newest packet sender now detects and alerts about this

**Comment by Terr4** [comment]
Correct yes! It seems I had an older version installed, with the new version I did get the prompt with the root info and got it working
