### ISSUE TITLE
Cannot Connect TCPIP

### ISSUE THREAD

**Issue by gkcabc** [dannagle/PacketSender#259]
#### What OS?

- [x] Windows
- [ ] Mac
- [ ] Linux (Which distro?)
- [ ] iOS (phone or ipad?)
- [ ] Android (phone or tablet?)

#### Description of issue
Can connect using localhost or 127.0.0.1. 
Cannot connect using LAN IP address (or hostname) (192.168.0.109) of PC.
Cannot connect to other devices on same LAN
Can connect using LAN IP with telnet. with everything.
Tried binding to 192.168.0.109, but no connect

**Comment by dannagle** [comment]
How about the TCP bundled packets?


![image](https://user-images.githubusercontent.com/1140573/138575613-8602ff37-b4b6-4a6c-8cce-ed47822c6888.png)
