### ISSUE TITLE
[BUG] Log traffic rolling not working

### ISSUE THREAD

**Issue by tixmcprods** [dannagle/PacketSender#274]
Hello,
The traffic log, with 100 entries or 10000 (10001 to be precise), doesn't roll.
Once full, not updated...
Thanks !
PS : using 7.2.3 Windows release.

**Comment by dannagle** [comment]
Fixed for next release. Good catch. It seems I broke that feature when I overhauled the logging to improve its performance.

Thanks for sending this in.
