### ISSUE TITLE
[BUG] Light theme, persistent TCP window color

### ISSUE THREAD

**Issue by Byxxi** [dannagle/PacketSender#289]
#### What OS?

- [x] Windows
- [ ] Mac
- [ ] Linux (Which distro?)
- [ ] iOS (phone or ipad?)
- [ ] Android (phone or tablet?)

#### Description of issue
When a connection is closed in the persistent TCP window, the background changes turns black, making the text in the window unreadable. With an open connection, the text is fine. 
Attached image shows both a closed connection and an open connection to compare:
![image](https://user-images.githubusercontent.com/19437416/159942657-f0ce84b8-b113-4d17-8995-a6ddeebc348c.png)

This happens with the dark theme as well, but the text color is white, so the text is readable.
Attached image shows both a closed connection and an open connection to compare:
![image](https://user-images.githubusercontent.com/19437416/159943154-af99a2d7-7ba3-48c0-89e8-dd84beae7ba0.png)

**Comment by dannagle** [comment]
You are absolutely correct. This was an oversight on my part.

**Comment by Byxxi** [comment]
Great to hear, really enjoying this as a piece of kit!

**Comment by dannagle** [comment]
This is now fixed in the development branch. Thanks for reporting this.

**Comment by dannagle** [comment]
Fixed in latest release.
