### ISSUE TITLE
Reduce of command line dependencies

### ISSUE THREAD

**Issue by lazna** [dannagle/PacketSender#291]
Make packetsender.com free of dependency on almost all bundled DLL, and thus make it better redistributable.

**Comment by dannagle** [comment]
OpenSSL and several run-time redistributables cannot be removed. However, if only command-line is desired, a good chunk of the GUI libraries could potentially be dropped.

Having a completely separate download for just command-line is too much hassle. Instead, a .bat file could be included to help purge the unneeded DLLs to make the directly command-line only.

**Comment by lazna** [comment]
Isnt a solution to check SSL libraries just in moment when SSL is employed (HTTPS packes is assembled), instead of check it on program startup?

**Comment by dannagle** [comment]
That is exactly how it works currently. If there are no SSL libraries, then you simply cannot use encrypted connections such as HTTPS or TLS. 

I bundle OpenSSL on Windows because I cannot use its built-in libraries (easily). For MacOS and Linux, I can use its built-in crypto libraries.

**Comment by lazna** [comment]
So, in case someone not utilizing sercured protocols, only packetsender.com will be enough for command line operations?

**Comment by dannagle** [comment]
You still need the run-time libraries. Not needing secure protocols only saves maybe 4 DLLs.

**Comment by lazna** [comment]
> You still need the run-time libraries. Not needing secure protocols only saves maybe 4 DLLs.

Make it as small as possible for cmdline usage, please.

**Comment by dannagle** [comment]
Development branch now has the fix so GUI libraries are not needed for command-line only use.

**Comment by lazna** [comment]
is there a list of DLLs, which could be omitted when packing console only reditributable zip?

**Comment by dannagle** [comment]
Eventually, yes. The README will be updated in the next release.

**Comment by lazna** [comment]
> You still need the run-time libraries. Not needing secure protocols only saves maybe 4 DLLs.

Are you cut this secure protocols dll too? This may be required even at point user assemble secure protocol packet.

**Comment by dannagle** [comment]
You can remove the secure DLLs now. That will remove any features that use SSL.

**Comment by lazna** [comment]
So for console operation without security functions, only main exe file in enough now?

**Comment by dannagle** [comment]
You still need the core run-time libraries. You won't need as near as many. I don't have the exact number, but the biggest ones, the graphics libraries, can be eliminated.

**Comment by lazna** [comment]
Thans for your effort. It would be great if this will be mented in readme file:

- list of files needed for unsecure command line operations
- list of files needed for secure command line operations

**Comment by dannagle** [comment]
https://github.com/dannagle/PacketSender/blob/master/README.md#ddls-that-can-be-removed-in-console-only-portable-mode

**Comment by lazna** [comment]
Perfect, thank you!!
