### ISSUE TITLE
[BUG] http requests on command line do not work

### ISSUE THREAD

**Issue by dannagle** [dannagle/PacketSender#299]
The command-line HTTP requests always trigger POST requests if data was ever saved to them. On top of that, it only ever hits the root-level HOST whatever the packet is sent to.

This is using saved packets. 

There are no options to build a manual HTTP request either.

**Comment by eriksunden** [comment]
Hi! Great piece of software 👍 

A question related to this bug. When saving HTTP Post request packet in the main applications, is that currently suppose to work with the command line application as well?
Works great in the GUI app, but loading the same saved packet in command line does not work (using latest release 8.0.9).
Also, does the command line application respect the setting of "Automatically adjusting ContentType when sending XML or JSON"?

**Comment by dannagle** [comment]
HTTP post requests is supposed to work the same on the command line as it does in the GUI (content-type adjustments included). Theoretically, you can save it in the GUI and then recall it in the command line. As of the current release, command-line HTTP requests is broken. This issue was opened to fix it.

**Comment by dannagle** [comment]
This is fixed for the next release.
