### ISSUE TITLE
packetsender.exe --usdelay 500000000 --name "TCP screen red"

### ISSUE THREAD

**Issue by mickae1** [dannagle/PacketSender#304]
#### What OS?
- Windows

#### Description of issue
THis command doesn't send a TCP message as it is configured, but a UDP message ....

but this command work:
packetsender.exe --name "TCP screen green" 

It send a tcp message as configured

Can you make the parameter --usdelay work with tcp message ?

**Comment by dannagle** [comment]
The intense traffic generator tool (both GUI and CLI) only supports UDP. I have no control over speed with TCP (at least not in user mode where Packet Sender operates), so there are no plans to support it.

**Comment by mickae1** [comment]
Why cant you do that ?

Do
Tcp connect
Tcp send
Tcp close
Sleep
While

**Comment by dannagle** [comment]
That loop isn't bandwidth, which is what the traffic generator tool is trying to manipulate. For TCP, each step requires an ACK. The transfer speed is also negotiated and auto-adjusted during the session. Then there is the problem if connection fails or the server is not present (causing connection timeouts).

Your 500 second example is not really the intended use of the traffic generator tool. If you need 500 seconds and separate connection attempts, your example would be better served not using the intense traffic generator and having a simple loop outside of `packetsender` CLI or using the GUI with 500 as the resend delay.
