### ISSUE TITLE
[IDEA] Loading only panels

### ISSUE THREAD

**Issue by C4lmani** [dannagle/PacketSender#309]
Hi. 
It would be a very helpful feature for PacketSender to be able to hide the programming part and to be able to launch only not modifiable panels, so less experienced users can use the program without risking of messing up the configuration.

Thank you for your patience

**Comment by dannagle** [comment]
Do you think adding a launch parameter, such as `packetsender.exe --panels-only` would work?

After installing, you would then modify the shortcut on the desktop by adding `--panels-only` parameter. This would tell Packet Sender to launch the startup panel without the normal GUI.

**Comment by C4lmani** [comment]
I think it would work, so there is no obvious way for the end user to 
potentially get access to the configurations.

Il 25/02/23 23:43, Dan Nagle ha scritto:

**Comment by dannagle** [comment]
Fix will be in the next release.
