### ISSUE TITLE
[IDEA] Send multiple packets in a single command

### ISSUE THREAD

**Issue by zethon** [dannagle/PacketSender#312]
**Desktop, Mobile, Command Line?**
Desktop

**Describe your idea**
It would be nice if you could send multiple packets at once. For example, we can select multiple packets and do things like "Delete Saved Packet" which will delete the selected packets. It'd be really create if there was a "Send Selected Packets" button, or even a context menu to "Send Packets".

**Comment by dannagle** [comment]
This is supported in Panel Generator. 

Launch the panel generator and then edit the button with the packets you want to send with a single click. 

Scripting a button is just the name of the saved packet on a line:

```
My Packet
My Other Packet
My Last Packet
```

More info about scripting a panel button here:
https://github.com/dannagle/PacketSender#scripting-a-panel

Hope that helps.
