### ISSUE TITLE
Some elements of the UI are overly scaled on a 4K screen with scaling set at 175%

### ISSUE THREAD

**Issue by Antorell** [dannagle/PacketSender#319]
#### What OS?

- [X] Windows
- [ ] Mac
- [ ] Linux (Which distro?)
- [ ] iOS (phone or ipad?)
- [ ] Android (phone or tablet?)

#### Description of issue

Some elements of the UI are overly over-scaled on Windows 10 at 4K with the scaling set at 175% with the new version 8.3.5 portable or 8.3.6. The previous version 8.1.1 from December scaled just fine on my OS/screen

This is what the new version (8.3.6) looks like at 4K with Windows 10 scaling set at 175%:
![Screenshot 2023-04-22 023133](https://user-images.githubusercontent.com/25066224/233752441-f27867c6-6c9b-4efa-a0ab-b8cb18702ceb.png)

This is how the previous version (8.1.1) looked like at 4K with Windows 10 scaling set at 175%:
![Screenshot 2023-04-22 023808](https://user-images.githubusercontent.com/25066224/233752484-780c93d0-5914-4c3f-bd02-fc33e20bbadb.png)

**Comment by dannagle** [comment]
2 steps forward. 1 step back. 

It is an oddity introduced after migrating from Qt5 to Qt6. Migrating fixed other issues but seemed to introduce this one. 


I am able to recreate this, so I can try to dig into it. Thank you for submitting this ticket.

**Comment by dannagle** [comment]
I think I have something that improves this. Would you mind testing it on your end?  Please email me so I can send you an alpha build:  hello@packetsender.com

**Comment by Antorell** [comment]
I sent you a mail.

**Comment by hjm0** [comment]
@dannagle Would you mind send me a alpha build, I have the same issue

**Comment by dannagle** [comment]
@hjm0 send me an email to the address I linked above. I'll get an early alpha to you. Reference this ticket when you do. So far, early reports say this alpha improves it. More tests would be helpful to me.

**Comment by dannagle** [comment]
New release posted with better 4K support for Windows and Mac. Linux users will need to wait until 2024 for improved rendering libraries. 

Please let me know if you see an improvement.

**Comment by Antorell** [comment]
It's perfect here. All the parts of the UI that didn't scale correctly like the "Saved packets" are now scaling correctly. 

Thanks.
