### ISSUE TITLE
[IDEA]Resend a packet a limited number of times

### ISSUE THREAD

**Issue by C4lmani** [dannagle/PacketSender#321]
**Desktop, Mobile, Command Line?**
Where will this feature exist?
Mac, PC
**Describe your idea**
I would like to be able to resend a packet a limited number of times, so I don't have to manually stop resending.
Thanks

**Comment by dannagle** [comment]
This exists in the Settings menu.

Go to File -> Settings -> Network

And look to the far right...
<img width="408" alt="image" src="https://github.com/dannagle/PacketSender/assets/1140573/0847ce96-097b-485b-b366-612be037cfdf">
