### ISSUE TITLE
[BUG] The version is always shown as 8.0.6

### ISSUE THREAD

**Issue by eribertomota** [dannagle/PacketSender#324]
#### What OS and Version?

Debian 12

#### Description of issue

In menu bar, click over Help > About. Is possible to see: PS Version 8.0.6.

**Comment by dannagle** [comment]
Version is assigned during build time with my offline pipeline that code-signs. If the build is good, I tag it and push the tags.

You make a really good point though. That workflow causes the version to be disconnected from the source code. 

I should instead commit the modified version files, tag, and then push.

I will leave this issue open until I can do that.

**Comment by dannagle** [comment]
The pipeline still bumps the version, which is needed for iterative tests, but my workflow now allows a commit and push with the final version number. It's a workable middle ground. Closing this issue.
