### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by celilo** [dannagle/PacketSender#328]
#### What OS and Version?
Windows 10 22H2

#### Description of issue
Winget installs the latest version 8.3.6, but the winget version appears as prior version 8.3.5, resulting in the package always showing as out of date and requiring the --include--unknown syntax.

**Comment by dannagle** [comment]
This probably happened because the original release had a corrupted .exe and required an immediate patch release. A new full release is in the works that would immediately fix this. Until then, a PR to the winget repo could fix this. I will see if that step is worth the effort or just waiting.

**Comment by celilo** [comment]
Thanks Dan. I appreciate your efforts.

**Comment by dannagle** [comment]
New release is now showing on winget. 

```
> winget search packetsender
Name          Id                     Version Match                 Source
-------------------------------------------------------------------------
Packet Sender NagleCode.PacketSender 8.4.3   Moniker: packetsender winget
```
