### ISSUE TITLE
[BUG] The app cannot be turned on.

### ISSUE THREAD

**Issue by tamthong1115** [dannagle/PacketSender#336]
#### What OS and Version?

Linux : Fedora 38
#### Description of issue
I have used 'chmod a+x' and installed both 'fuse' and 'fuse-devel', but I am still unable to launch the application even the app icon appears on the desktop.

    ./Packet_Sender-v8.4.3-x86_64.AppImage 

    /usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
    QSocketNotifier: Can only be used with threads started with QThread
    qt.qpa.qgnomeplatform.theme: The desktop style for QtQuick Controls 2 applications is not available on the system (qqc2-desktop-style). The application may look broken.

I tried to install the package 'qqc2-desktop-style', but it still doesn't work

**Comment by dannagle** [comment]
I downloaded and installed a fresh Fedora into a VM. I was able to get it to run with bypassing the GUI check. 

![image](https://github.com/dannagle/PacketSender/assets/1140573/17c917fb-a707-4b48-aac3-923ac9b361d3)

**Comment by tamthong1115** [comment]
Thanks, it works perfectly.
