### ISSUE TITLE
[BUG] Log not updated after day change when resending messages

### ISSUE THREAD

**Issue by rsngt** [dannagle/PacketSender#341]
#### What OS and Version?
Windows 10, 
8.5.2
#### Description of issue
I am sending a message repeatedly with the resend function (every 15 minutes). The log in the UI is updated with each new message sent, until midnight, when no new messages are displayed in the log. The messages are being sent, it's just that the log doesn't refresh in the UI. If I clear the log in the UI then the subsequent messages are shown in the log (until the next midnight).

This has been an issue for the last few versions.

**Comment by dannagle** [comment]
This is an amusing bug. I found the problem, and I know the fix. 

The log table rolls over to "00:00:00" at midnight. The new packets actually are getting logged. They are getting sent to the bottom out of view. Over the course of 2 days, the logger will become a jumbled mess. 

The proper fix is to include the full date so the sort will stay correct. Including the full date has been requested before (such as in #314), so I will try to have that in the next release. That will fix this problem too.

**Comment by Secure-Mobility** [comment]
> This is an amusing bug. I found the problem, and I know the fix.
> 
> The log table rolls over to "00:00:00" at midnight. The new packets actually are getting logged. They are getting sent to the bottom out of view. Over the course of 2 days, the logger will become a jumbled mess.
> 
> The proper fix is to include the full date so the sort will stay correct. Including the full date has been requested before (such as in #314), so I will try to have that in the next release. That will fix this problem too.

Great, that's good news. I look forward to the updated release :-)

**Comment by dannagle** [comment]
This fix is now in the latest release. Closing.
