### ISSUE TITLE
[BUG] Cannot use command line tool

### ISSUE THREAD

**Issue by JPersson77** [dannagle/PacketSender#347]
#### What OS and Version?
Win11 22631.2861 (23H2)
PacketSender (in portable mode) v8.6.3

#### Description of issue
It works perfectly well to use the GUI to send a simple ascii text over tcp, and I can also use the command line with the -n switch to recall the saved packet - but I cannot use the command line. Whatever I've tried I get the error: "Error: Could not resolve address:"

![Skärmbild 2023-12-26 234128](https://github.com/dannagle/PacketSender/assets/77928210/77cd0a08-2ebe-44cf-acff-4f4ff2bd44f5)

![Skärmbild 2023-12-26 234808](https://github.com/dannagle/PacketSender/assets/77928210/b4a3f9d3-3f5e-43cd-846c-7c7e849ae0d6)

This is the relevant code for the error message:
https://github.com/dannagle/PacketSender/blob/b10bdc6635d4ede5eca19c8f2fda9d0eb720c722/src/main.cpp#L807

**Comment by dannagle** [comment]
You are correct. I withdrew last week's release and pushed a new one with the address fix. It seems in my testing I picked up a debug build. 


Thank you for letting me know.

**Comment by JPersson77** [comment]
Thanks a lot for your quick fix! Can confirm it working properly.
