### ISSUE TITLE
[BUG]Starter Panel from Command Line

### ISSUE THREAD

**Issue by fgolman** [dannagle/PacketSender#354]
#### What OS and Version?
Win 10
PS Version 8.5.2
Qt Version 6.5.2

#### Description of issue
Using the --starterpanel option, as documented, on command line states:

Packet Sender: Unknown option 'starterpanel'.

**Comment by dannagle** [comment]
Take a look here about exe vs com version. 

https://github.com/dannagle/PacketSender/discussions/301#discussioncomment-5232956


If still having issues, will you paste your command line attempt for me to see?

**Comment by fgolman** [comment]
That works.

Windows wants to use the .exe version so by forcing it explicitly I got the .com version.

Thank you
