### ISSUE TITLE
[BUG] To IP column in Log window is empty on Mac version but To Address column on PC version has expected data

### ISSUE THREAD

**Issue by jsolderitsch** [dannagle/PacketSender#359]
#### What OS and Version?
PacketSender v8.6.5 Mac OS 14.3.1

#### Description of issue
Like title says. Log display is different on Mac than on PC.

<img width="1248" alt="Screenshot 2024-02-10 at 3 45 48 PM" src="https://github.com/dannagle/PacketSender/assets/23091236/7da43ce5-8555-4763-a4d6-0a7edda791a4">

On the PC the log window uses the column label To Address and there is data shown in this column (screen shot not included but could be)

Using Windows 11 and Mac Sonoma 14.3.1.

**Comment by dannagle** [comment]
It is possible I goofed up a backwards compatibility check. 


Does it fix itself if you reset your Packet Sender Mac settings?

1. Close Packet Sender.

2. Make a settings file backup
```
cp ~/Library/Application\ Support/PacketSender/ps_settings.ini ~/Library/Application\ Support/PacketSender/ps_settings.ini.backup
```


2. Delete the settings
```
rm ~/Library/Application\ Support/PacketSender/ps_settings.ini
```

3. Launch Packet Sender again.

**Comment by jsolderitsch** [comment]
Yes, this step sequence does cause a To Address column to appear instead of a To IP column and then data appears there as it does when I run packetsender on the PC. Thanks for the quick response.
