### ISSUE TITLE
It is possible to communicate as TLs1.3 client? I want to test my TLS1.3 custom server[IDEA]

### ISSUE THREAD

**Issue by NataliaAR22** [dannagle/PacketSender#369]
**Desktop, Mobile, Command Line?**
Where will this feature exist?

**Describe your idea**

**Comment by NataliaAR22** [comment]
It would be very useful a Desktop solution to be able to communicate as a client and or sever.
Adding an option for selecting TLS1.2 or TLS1.3.
A second option where it could be possible to add the certificates.
An option similar to the actual one for being able to select the IP address and Port to communicate
![Captura de pantalla 2024-05-23 094932](https://github.com/dannagle/PacketSender/assets/114577584/1e7c9d90-d5d6-4627-aae1-5555e0d027ba)
And a place to add the packet to send as the ASCII or HEX box..

**Comment by dannagle** [comment]
Thanks for opening this issue.

This screenshot looks like you are using Windows. Packet Sender for Windows uses OpenSSL which can send TLSv1.3. You can go to Help --> About, and then you can see the OpenSSL (or native SSL for other installations) library in use.

The currently shipping one inside Packet Sender is v3.0.7, which does support TLSv1.3. If you are looking for specific cipher suites, you can browse the changelog here:  https://www.openssl.org/news/changelog.txt

If you want to manipulate the certificates used by Packet Sender server, `cert.pem` and `key.pem` can be found at `%LOCALAPPDATA%\PacketSender\`
