### ISSUE TITLE
windows console file copy issue

### ISSUE THREAD

**Issue by lazna** [dannagle/PacketSender#373]
#### What OS and Version?
Windows 10

#### Description of issue
Just discovery the issue with copying packetsender binaries from one directory to another. Name of file "libstdc++-6.dll" contain plus sign which is serious issue by using built-in "copy" windows command without filename is doublequoted. Copy comand interprete plus sign as "file combining" operator (https://ss64.com/nt/copy.html). Plus sign issue is NOT described as a problem in documentation. 

Its a problem, because it DOES NOT PRINT ANY ERRRO MESSAGE, but files may by changed durring coppying. Today I spent almost two hours to find-out what is wrong :-/

Think about rename of such file(s) please, thank you....

**Comment by dannagle** [comment]
Hello, 

I agree that the non-standard filename is annoying. I don't like it either. Unfortunately, that DLL is used by a lower library and cannot be renamed. I'm sorry that it cost you 2 hours, but I cannot fix this.

**Comment by lazna** [comment]
Got it. Maybe is a good idea to add notice "when copying files, always doublequote it because of issue with 'libstdc++-6.dll' plus signs and windows 'copy' utility", into a section "Console-only portable Mode" here https://github.com/dannagle/PacketSender

**Comment by dannagle** [comment]
Good idea. I added a note to the README. Closing this issue.
