### ISSUE TITLE
Aborted (core dumped)

### ISSUE THREAD

**Issue by bartounet16** [dannagle/PacketSender#38]
I have compiled packetSender on Ubuntu 15.10
The compilation work good but at the execution i have
Aborted (core dumped)
Could you help me

**Comment by dannagle** [comment]
Are you using the server edition of Ubuntu? Compiling has known issues with the server edition.

**Comment by bartounet16** [comment]
Hello 
i have the same problem with

Ubuntu server 
root@www:~/PacketSender-4.9/src# ./PacketSender -h
Aborted (core dumped)
root@www:~/PacketSender-4.9/src
# cat /etc/issue.net
Ubuntu 14.04.4 LTS


Unbuntu Desktop 15.10
root@bartounet-HVM-domU:/home/bartounet/PacketSender-Linux/PacketSender-4.9/src
# cat /etc/issue.net
Ubuntu 15.10

**Comment by dannagle** [comment]
Packet Sender does not work on Ubuntu Server. There is a graphics library dependency that has not been fixed. Are you having problems on Ubuntu Desktop too?

**Comment by bartounet16** [comment]
Yes but i want only use command line for a script and no gui
it does not works with ssh

**Comment by dannagle** [comment]
OK, then it won't work for you in its current state. All the graphics dependencies would need to be removed. I don't have time for that right now. I'll leave this bug open.

**Comment by Jufo84** [comment]
I have the same problem on the distribution of Raspbian Jessie and Jessie Light (Debian), you can ask for a solution to the problem ...

**Comment by dannagle** [comment]
@Jufo84  What particular ISO are you using? I can install in a VM. 

This issue keeps popping up, so you are not that small a minority. I think a few ifdef macros and Makefile tweaks would fix this pretty easily.

**Comment by Jufo84** [comment]
The program only works in graphic mode on Raspbian Jessy and Jessy Lite (kernel 4.1, https://www.raspberrypi.org/downloads/raspbian/). With SSH connection, I get a message "aborted"

**Comment by Jufo84** [comment]
Hi,

Any progress in resolving this bug?

Best Regards,
Robert

**Comment by dannagle** [comment]
Yes, I have a fix. I haven't had time to put together a release, fix the Makefile, or anything like that. Packet Sender is a volunteer effort. Paid gigs get priority. I'm sure you understand. 

If you are comfortable tweaking code, here is what to do. This is removing the GUI stuff that happens during console mode causing it to crash.  `QApplication` is now `QCoreApplication` .  Then stylesheet stuff is removed. 

Edit lines 48 through 62 in `main.cpp` to look like this
````
    //QApplication a(argc, argv);
    QCoreApplication a(argc, argv);
    QStringList args = a.arguments();
    QDEBUGVAR(args);

    qRegisterMetaType<Packet>();
/*

    QFile file(":/packetsender.css");
    if(file.open(QFile::ReadOnly)) {
       QString StyleSheet = QLatin1String(file.readAll());
     //  qDebug() << "stylesheet: " << StyleSheet;
       a.setStyleSheet(StyleSheet);
    }
*/
````
Recompile, and it should work for you. I tested it on an Ubuntu Server that does not have a GUI.

**Comment by dannagle** [comment]
`main.cpp` has been updated in the master branch. It bypasses starting the GUI if using console params. Hopefully, that is the ultimate fix.

**Comment by Jufo84** [comment]
Yuupi :)
It works! (Raspbian Jessie Lite,kernel 4.4)
Thank you very, very much :)

**Comment by dannagle** [comment]
Release published. Closing this issue.
