### ISSUE TITLE
Segfault on Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by primetime00** [dannagle/PacketSender#39]
I've run the build script, and everything compiles just fine.  Whenever I try to run the executable, it segfaults.  Not sure why.

```
PacketSender-Linux/PacketSender-4.9/src$ ./PacketSender
Segmentation fault
```
I imagine this is a QT5 issue.

Any suggestions?

**Comment by dannagle** [comment]
Are you running on Ubuntu Server? 

The build system has problems on Ubuntu Server. It looks for a graphics library, which I haven't had time to fix for the server edition.

**Comment by primetime00** [comment]
No, just plain Ubuntu.  I am using XFCE.  Other that that, it's as vanilla as you can get.

**Comment by dannagle** [comment]
I've never tried it on XFCE. 

I test it on the mainstream Ubuntu Desktop LTS. XFCE is supposed to be lightweight, so there may be problems. You may need to install more Qt libraries, which would defeat the purpose of going lightweight.

**Comment by dannagle** [comment]
Please see this issue #38  . I just pushed a commit to master that should fix this. Replace your main.cpp and recompile.
