### ISSUE TITLE
Response Time on command line.

### ISSUE THREAD

**Issue by digipigeon** [dannagle/PacketSender#4]
It would be really useful if there was some way of getting access to the response time from the command line.

**Comment by dannagle** [comment]
Outputting a timestamp of the response packet should be pretty easy. I'll try to add that.

**Comment by dannagle** [comment]
Added. Will be in the next release.

**Comment by digipigeon** [comment]
Hi Dan, sorry to re-open this enhancement, but maybe I didn't make the request understandable first time around. I see that a time is displayed on the command line now, however what I was looking for was a round trip time, is this possible with a different parameter, or could I suggest this as a feature.

**Comment by dannagle** [comment]
The format of that time stamp is fixed. A round trip time would need to be added in the next round of feature updates. Please open another request. An example of what output you expect would be useful. 

I've run out of spare time to work on this project right now. I may have time to make a preliminary release that supports that feature in October.
