### ISSUE TITLE
{{RANDOM}} usage in hex field

### ISSUE THREAD

**Issue by sadortun** [dannagle/PacketSender#42]
Hi !

It would be nice to be able to specify bytes that should be replaced with a random value in the HEX field.

Example :  `00 ab cd ef  10 RR RR cc`

Each bytes with a `R` value could be replaced by a random byte size value.

**Comment by sadortun** [comment]
In addition,  it would be even more awesome if we could also have a UNIQUE field.

For example: `00 ab cd ef 10 UU UU cc`  would replace the  contiguous `U` with a unique value. If all values are exhausted, you could wrap around.

**Comment by dannagle** [comment]
This is an interesting idea, but I think it is a bit narrow. There are higher priority requests I would do before I'd try to do this one.

**Comment by sadortun** [comment]
Thanks for your quick answer. I might be able to submit a PR next week. Can you point me out where would be the right place to do the decoding and replacement ?

**Comment by dannagle** [comment]
Take a look at the function `QString Packet::macroSwap(QString data)`

It is in file `packet.cpp`, line 623
