### ISSUE TITLE
Source IP spoofing while sending TCP packets

### ISSUE THREAD

**Issue by DineshShende** [dannagle/PacketSender#43]
Hi,
As of now we are sending packets to target with source IP as machine where we run PacketSender. Is there any provision so that we can change source IP address?

**Comment by dannagle** [comment]
This would require access to the packet headers(with a library such as pcap), which Packet Sender has no plans to support. 

If you wish to force bind an address that you are running (useful with multiple network cards), that could potentially happen, but the address would still be your machine.

**Comment by DineshShende** [comment]
Ok..I thought their will be any easy way for that.Should I close this issue?
