### ISSUE TITLE
Basic usage with nc listening?

### ISSUE THREAD

**Issue by srsudar** [dannagle/PacketSender#44]
I think I'm misusing the tool, but I'm not sure how. 

Say that I start listening to port 8887 with `nc`:

```
nc -k -l 8887
```

If I now send something to that port, `nc` spits it out:

```
echo "hello" | nc localhost 8887
```

On my process listening to `8887`, out comes `hello`.

Using the PacketSender GUI, if I try sending a packet to `localhost` port 8887, with either UDP or TCP, I don't get anything out of my `nc` listening on 8887. Am I misunderstanding how `nc` and PacketSender interact with each other, or am I misusing PacketSender?

**Comment by dannagle** [comment]
My test:

![packetsender_nc](https://cloud.githubusercontent.com/assets/1140573/16317477/f5beb718-3950-11e6-87c0-15d49e6fe004.png)

"localhost" frequently translates to an IPv6 address while Packet Sender tends to favor IPv4 unless explicitly told to use IPv6. Try testing with routable IPv4 addresses.

**Comment by srsudar** [comment]
Yep that did it! I had IPv4 mode selected in the bottom right, but when I sent it to my address as specified by `ifconfig` I started receiving the packets. I also then realized that I had to use `nc -u -k -l 8887` to listen for UDP packets, as the default without the `-u` flag only responded to TCP packets.
