### ISSUE TITLE
Not showing all data

### ISSUE THREAD

**Issue by Bernardtb4** [dannagle/PacketSender#46]
Hi 
My device sends (*GS06,351535058775057,121402190716,,SYS:G6S;V2.20;V1.0.6,GPS:A;11;S00.000000;E00.000000;0;0;1390;0.85,COT:,ADC:10.14;3.81,DTT:4000;C0;0;0;0;1#)
and the program does not show it 
But when my device sends *GS06,351535058775057# it responds and show it on your tool 
See attached 
i need the tool to show me ALL data that the device sends 
![packet sender](https://cloud.githubusercontent.com/assets/20537808/16949921/c77d596e-4dbd-11e6-8a4c-0cf2388162d5.jpg)

**Comment by dannagle** [comment]
Is there a long delay? Packet Sender will close the socket after a period of time. It may be cutting off the device. You can try enabling the "Persistent TCP" checkbox. That feature is experimental, but it may work better for you.

**Comment by Bernardtb4** [comment]
2 strings data is send short string (Heart-beat packet)1 : SER:*GS06,351535058775057#  2 Long string Device data :  SER:*GS06,351535058775057,121402190716,,SYS:G6S;V2.20;V1.0.6,GPS:A;11;S00.000000;E00.000000;0;0;1390;0.85,COT:,ADC:10.14;3.81,DTT:4000;C0;0;0;0;1#
The sort string is shown on the program but the long string does not show , i have tried hex also but it does the same

**Comment by dannagle** [comment]
I can't replicate this. What is the long string in hex you are trying to send?

**Comment by Bernardtb4** [comment]
Longstring is the device full data 
Short string is just a "hi" to the server

**Comment by dannagle** [comment]
I sent this hex data. Is this the correct data string?:
53 45 52 3a 47 53 30 36 2c 33 35 31 35 33 35 30 35 38 37 37 35 30 35 37 2c 31 32 31 34 30 32 31 39 30 37 31 36 2c 2c 53 59 53 3a 47 36 53 3b 56 32 2e 32 30 3b 56 31 2e 30 2e 36 2c 47 50 53 3a 41 3b 31 31 3b 53 30 30 2e 30 30 30 30 30 30 3b 45 30 30 2e 30 30 30 30 30 30 3b 30 3b 30 3b 31 33 39 30 3b 30 2e 38 35 2c 43 4f 54 3a 2c 41 44 43 3a 31 30 2e 31 34 3b 33 2e 38 31 2c 44 54 54 3a 34 30 30 30 3b 43 30 3b 30 3b 30 3b 30 3b 31 23

![longstring](https://cloud.githubusercontent.com/assets/1140573/16955778/95480d9e-4d9b-11e6-8f9d-9659299391a4.png)

**Comment by Bernardtb4** [comment]
I'm getting the full data string now ? don't know why it did not give it to me from the beginning but the tool is now showing all the data to me but now the data is nonsense ? see the 2 screens the one in front is the correct data but the 2nd screen is symbols (��?�"M��?�"M��?�"M��?�"M��?�"M��?�"M��?�"M��?�"M�)
 Why ?
![image](https://cloud.githubusercontent.com/assets/20537808/17021668/c5c0e2f2-4f49-11e6-98a9-9ce04ba686d0.png)

**Comment by dannagle** [comment]
Bizarre. Packet Sender has an EBCDIC encoding option, but it doesn't get invoked during incoming, and that string does not match EBCDIC quite right. 

You could try it with portable packet sender with the default settings to see if it behaves better.

**Comment by dannagle** [comment]
A stability fix was pushed to master branch. You can grab the code now or wait for new installers.
