### ISSUE TITLE
--version option

### ISSUE THREAD

**Issue by lazna** [dannagle/PacketSender#51]
It does not show version number:

`C:\utils\PacketSender>packetsender --version
Packet Sender version`

**Comment by dannagle** [comment]
C:\Program Files (x86)\PacketSender>packetsender --version
Packet Sender version 2016-07-23

What OS are you running?

**Comment by lazna** [comment]
Windows 7

**Comment by dannagle** [comment]
"C:\" is sometimes a protected directory in Windows, though the result would be no commands would work. 

Does the portable version work when ran from a sub-directory out "Downloads"?

**Comment by lazna** [comment]
No, it does not work at all

```
C:\utils\PacketSender>PacketSender --version
Packet Sender version
```

BTW: In c:\ only disc writes could be protected, ABSOLUTELLY NOT a STDOUT of program started from such path.

**Comment by dannagle** [comment]
I think you may be calling the GUI version. Use the lowercase version of packet sender.  Even better, explicitly call the ".com" version...

```
C:\utils\PacketSender>packetsender.com --version
Packet Sender version 2016-07-23
```

See if using "packetsender.com" executable works better for you.

**Comment by lazna** [comment]
No change, same behaviour

C:\utils\PacketSender>packetsender.com --version
Packet Sender version

**Comment by dannagle** [comment]
I am out of ideas. I did a fresh download of the portable version in to a fresh VM, and it worked for me. Perhaps there is something unique happening with your system.

**Comment by lazna** [comment]
Juste tested on Windows 7/64bit, Windows 7 32bit, Windows 2003/32bit. All test performed with "packetsender.com --version", on fresh downloaded copy of "pocket" version, all test have same result "Packet Sender version" (without any version number or date string). I do not thing this is caused by specific OS instance. Could you test it on different machine?

**Comment by dannagle** [comment]
I tried Win10 x64 on one computer, WinXP x32 on another, and Win7 x64 on another. I downloaded the portable version for each, and they all worked for me. 

Is your system's language set to something other than English? One of the functions I am using in the code had a bug report filed regarding non-English systems. It is possible for locale's other than English, the output of the date could get confused. The bug says "Resolved", but maybe it isn't.

**Comment by lazna** [comment]
Yes, all of my systems have all Regional options set to Czech. Could it be the issue?

**Comment by dannagle** [comment]
I can't test this right now, but it sounds possible.

**Comment by lazna** [comment]
Just downloaded fresh, portable copy of Packetsender but still does not print out version info:

C:\Scripts>\utils\PacketSender\packetsender -v
Packet Sender version  / SSL version:OpenSSL 1.0.2h  3 May 2016

**Comment by dannagle** [comment]
The version is a date that is outputted using a macro. Perhaps the macro behaves odd with non-English. I'll try to find another way.

**Comment by lazna** [comment]
FYI: Actual (fileinfo: 09.08.2017  03:35 1,444,864 packetsender.com) version still does not printing version on Czech windows version.

**Comment by dannagle** [comment]
Latest release is no longer using a string. Hopefully, you are now just getting a version number.

**Comment by lazna** [comment]
Working fine now ;-) Thanx

C:\>\utils\PacketSender\packetsender.com -v
Packet Sender version v5.6.2 / SSL version:OpenSSL 1.0.2j  26 Sep 2016
