### ISSUE TITLE
SSL Server / client support

### ISSUE THREAD

**Issue by piotrva** [dannagle/PacketSender#52]
There is a lack of TLS server/client support, that would be useful when debugging secure network applications.

**Comment by dannagle** [comment]
I think this is a great idea. 

Client support will be far easier to add than the server. OpenSSL + GPLv2 legal issues will need to be worked out for server support.

**Comment by dannagle** [comment]
The latest version now has SSL client support. I will have to investigate server support.

**Comment by dannagle** [comment]
https://github.com/dannagle/PacketSender/releases/tag/v5.4
