### ISSUE TITLE
Maximize TCP Persistent window

### ISSUE THREAD

**Issue by waltonad0283** [dannagle/PacketSender#56]
Often times, I find myself expanding the TCP persistent window when looking at a lot of data, or wishing to minimize it.  There is currently only a close button.  Any chance to add in max/min options as well?

**Comment by dannagle** [comment]
The button in Windows has been added to the main branch.  It'll be in the next release. Double-click title bar in Mac to maximize (was always there).

**Comment by dannagle** [comment]
Now released.
