### ISSUE TITLE
Qlab Controling PacketSender

### ISSUE THREAD

**Issue by derekleather** [dannagle/PacketSender#59]
I am looking to use Qlab to control packet sender to send a hex string to control equipment such as projectors to turn on off etc.

I have some apple script that will activate PacketSender but I am struggling to then get a saved packet to send.

Is this possible using apple script?

**Comment by dannagle** [comment]
The command line interface may work better for you. You can send previously saved packets from it. I don't have a Mac nearby, so I am doing the syntax from memory:

```
/Applications/PacketSender.app/Contents/MacOS/PacketSender   -n "name of saved packet" -w 500
```

-n is the flag to specify packet name
-w means wait for a response. 

Use --help to get all the options.

**Comment by derekleather** [comment]
Hi thanks for the response. 
Maybe I am being stupid but how do I access the CLI on a mac? is this terminal?

**Comment by dannagle** [comment]
Yes, launch the Terminal app. 

Spotlight search (top right) -> Terminal

That will get you the mac command prompt.

**Comment by derekleather** [comment]
perfect thanks.
