### ISSUE TITLE
Unable to use host name to send UDP packets

### ISSUE THREAD

**Issue by sylvester328** [dannagle/PacketSender#71]
Tested on Windows 8.1, firewall turned off, latest version (build date 2017-02-21).

When putting a host name as target, it resolves to the correct IP address (shown at bottom status bar) but no packets received at the target machine.  When put in the IP address instead, packets arrive.

Doing similar test with nping/nmap on the same machine, nping works with same host name.

**Comment by dannagle** [comment]
This is the first version of Packet Sender to DNS resolve on-demand when sending (required for SSL/TLS). All previous versions immediately resolved and saved only the IP address . 

Something is probably getting confused in UDP socket setup when a non-IP string is passed to it.
