### ISSUE TITLE
Window list is not shown in macOS dock

### ISSUE THREAD

**Issue by vadi2** [dannagle/PacketSender#72]
PacketSender does not show the list of opened windows when right-clicking on the application in the dock, unlike what is standard for mac apps:

![macos sierra running - oracle vm virtualbox_004](https://cloud.githubusercontent.com/assets/110988/23829662/3907c224-06f8-11e7-8653-495d2766c490.png)

Works fine on Ubuntu:

![workspace 1_003](https://cloud.githubusercontent.com/assets/110988/23829664/41586820-06f8-11e7-8440-15c74395e3fd.png)

See https://bugreports.qt.io/browse/QTBUG-59433 bug report.

**Comment by dannagle** [comment]
Thanks for digging in to this. I'll leave this bug to Qt and update whenever they release a new version for Mac.

**Comment by dannagle** [comment]
With Qt 5.9.1 released, it is still behaving this way. I'm closing this bug since I do not plan to fix this bug myself.
