### ISSUE TITLE
Error on compile PacketSender in Ubuntu server 14.04.5

### ISSUE THREAD

**Issue by sdeca** [dannagle/PacketSender#73]
On make process i have this error:

main.cpp: In function ‘int main(int, char**)’:
main.cpp:126:35: error: ‘sslLibraryBuildVersionString’ is not a member of ‘QSslSocket’
             versionBuilder.append(QSslSocket::sslLibraryBuildVersionString());
                                   ^
main.cpp:384:58: error: ‘sslLibraryBuildVersionString’ is not a member of ‘QSslSocket’
             OUTIF() << "The expected SSL version is " << QSslSocket::sslLibraryBuildVersionString();
                                                          ^
main.cpp:510:40: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
                 while(now.elapsed() <= wait && (sock.state() == QAbstractSocket::ConnectedState)) {
                                        ^
main.cpp:573:36: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             while(now.elapsed() <= wait) {
                                    ^
make: *** [main.o] Errore 1

I try to install last version also with script BuildPacketSender.sh, are there some dependency that I miss ?
Thanks

**Comment by dannagle** [comment]
What is  your qmake version? Packet Sender requires a fairly recent Qt. That particular function is needs 5.4: http://doc.qt.io/qt-5/qsslsocket.html#sslLibraryBuildVersionString

You may also try downloading the Linux binary release. It is a 64-bit container and may work for you.

**Comment by sdeca** [comment]
I checked and i'm using QMake version 3.0 - Qt version 5.2.1, fine i'll upgrade Qt on 5.4 and then i recompile PacketSender.
Thanks
