### ISSUE TITLE
Windows console output format

### ISSUE THREAD

**Issue by lazna** [dannagle/PacketSender#79]
Dealing with packetsender in windows console, especially -x or -A options, but as output still got mixed (both hexa and ascii) output. What am I doing wrong?

C:\Scripts>\utils\PacketSender\packetsender -u -x -w 1000 255.255.255.255 10001 "01 00 00 00

or

C:\Scripts>\utils\PacketSender\packetsender -u -A -w 1000 255.255.255.255 10001 "01 00 00 00

both of them got me same output. I need only hex on STDOUT. What am I doing wrong?

**Comment by dannagle** [comment]
Those switches specify the input format. The output format is always the same. It looks like you are also missing a closing quote at the end.

**Comment by lazna** [comment]
Could you ment it in documentation, please?

"Parse INPUT data as...." will be much better than "parse data as..."

If you could add switch(es) to output hexa OR ascii, it will be helpfull for packets parsing....
