### ISSUE TITLE
UDP packet size

### ISSUE THREAD

**Issue by reetikavats** [dannagle/PacketSender#84]
Hi Dannagle,
Just for info purpose. I am sending ethernet data through FPGA. Is  there any setting of max data byte length supported by GUI  or its just the limit of UDP itself.

**Comment by dannagle** [comment]
A UDP packet size max is around 1,500 bytes.  You can configure your switch to try to get up to around 9,000 bytes. 

The Packet Sender GUI always reads the entire packet and can display up to around 10,000 bytes per packet. The GUI has no max size configurations.
