### ISSUE TITLE
Please use .AppImage filename extension, not .run

### ISSUE THREAD

**Issue by probonopd** [dannagle/PacketSender#86]
Please use the `.AppImage` filename extension, not `.run`. Then it can be included in the central directory of available AppImages at https://github.com/AppImage/AppImageHub.

Reference:
https://travis-ci.org/AppImage/AppImageHub/builds/266230784#L534-L541

**Comment by dannagle** [comment]
Updated:
https://github.com/dannagle/PacketSender/releases/download/v5.4.1/PacketSender_Linux_v5_4_1_2017-08-08.AppImage

**Comment by probonopd** [comment]
Thank you, working well now. Added to https://github.com/AppImage/AppImageHub.
