### ISSUE TITLE
ssl question

### ISSUE THREAD

**Issue by JacksonLv** [dannagle/PacketSender#88]
I am a greener of ssl and I want to use your tools to test ssl socket(just transport layer ). As I know this tools will set a ssl tcp server as long as I turn it on ,right? I set the certificate/key that I generate by openssl .Then I try to use PacksetSender to send SLL packet to the SSL server, but I got error "Could not connect".So am I using it in a wrong way?
![ps](https://user-images.githubusercontent.com/12758420/30469820-cde2e90e-9a24-11e7-980f-1922af534068.png)

**Comment by dannagle** [comment]
I think I found the problem. The installer-based Packet Sender is not generating certs correctly. Do you have better luck when using the portable version? https://packetsender.com/download

**Comment by dannagle** [comment]
If you copy the files cert.pem and key.pem from the portable version to %AppData%\Local\PacketSender, the installer-based one will start working.

**Comment by JacksonLv** [comment]
Thanks for your reply, I am using version "PacketSender_5_4_2_2017-09-01" when I  found the problem. Did you upgrade the lattest version? I found it's name is still "PacketSender_5_4_2_2017-09-01".

**Comment by JacksonLv** [comment]
Thanks for your reply !! I just tested the portable version and it works great! There are other questions if you can help will be grateful!
1.I only found ps.pem in the folder.Is it the same as cert.pem?
2.Can you add a function to ssl server which will replay the message that the client send to it so that I can know if the client also can receive data correctly with ssl?
waiting for your reply!

**Comment by dannagle** [comment]
1. I just downloaded the latest portable version. I see ps.pem and key.pem listed.

```
C:\Users\Dan\Downloads\PacketSenderPortable>dir *.pem
 Volume in drive C is Windows

 Directory of C:\Users\Dan\Downloads\PacketSenderPortable

08/04/2017  07:33 PM               887 key.pem
08/04/2017  07:33 PM               969 ps.pem
               2 File(s)          1,856 bytes
```

2. An echo service has been requested many times. Not sure when I can get to it. This is a hobby project I do in my spare time. Perhaps a patron will one day sponsor that feature to speed that feature along.

**Comment by dannagle** [comment]
Latest release should now have openssl libraries and certs loading correctly.

**Comment by Serjaru** [comment]
Help anyone please!
I have really (not selfsigned) cert and key and CA, but show self-signed! Why?

**Comment by dannagle** [comment]
Convert them to pem files. That's all that has been tested. 

2 options...

1. Replace the ps.pem and key.pem files used by Packet Sender. 

1. Options in the GUI:
![image](https://user-images.githubusercontent.com/1140573/78610558-bc387e80-782a-11ea-926a-8e6ad33846a5.png)

I would first attempt to replace the ps.pem and key.pem files.

**Comment by Serjaru** [comment]
> 
> 
> Convert them to pem files. That's all that has been tested.
> 
> 2 options...
> 
>     1. Replace the ps.pem and key.pem files used by Packet Sender.
> 
>     2. Options in the GUI:
>        ![image](https://user-images.githubusercontent.com/1140573/78610558-bc387e80-782a-11ea-926a-8e6ad33846a5.png)
> 
> 
> I would first attempt to replace the ps.pem and key.pem files.

i was browse Local cert and Private key, but selfsigned!

SSL CA Certificate ? what need? I have CA file too
