### ISSUE TITLE
How to install and open packet sender on Ubuntu 16.04?

### ISSUE THREAD

**Issue by bandht** [dannagle/PacketSender#94]

**Comment by dannagle** [comment]
Download the .AppImage and then chmod a+x.  Run it. 

That is the preferred method. If AppImage does not work, there are compile instructions in the readme.md

**Comment by imnotkk** [comment]
Those compile instructions are provides a link to an Non-existing link during wget.

**Comment by dannagle** [comment]
Compile instructions are a guide. Here is a the latest code release:
https://github.com/dannagle/PacketSender/archive/v5.7.52.tar.gz

**Comment by imnotkk** [comment]
Thanks!
