### ISSUE TITLE
I do not know much about this subject

### ISSUE THREAD

**Issue by gmigliarini** [dannagle/PacketSender#96]
I do not know muI put ASCII = L1 and IP = 192.168.1.166 and Port 1234 and TCP and my electronic relay works correctly.

My question is if I want to send an HTML line as I get it, it's something like:

http://192.168.1.166?D2 ???

Thank you

George
California, USA
gmigliarini@cox.net

**Comment by dannagle** [comment]
I do not quite understand. Are you trying to mimic the HTTP protocol?

**Comment by gmigliarini** [comment]
Thank you very much for your help, I want to send a feed via the website to turn on and off the relays of my project and I do not know how to write in HTML.
Thank you very much George

**Comment by gmigliarini** [comment]
The idea is to send a line such as http: //192.168.1.166/ ???  to turn a relay on and off and this program does it correctly, but I need to put.

 

ASCII = L1 

 

IP = 192.168.1.166 

 

Port 1234 

 

TCP

 

See  Photos Attach.

 

Thank You

 

George

**Comment by gmigliarini** [comment]
I tell you a little more, my idea is to make a web page with a single button that says Relay On and Relay Off and I must send the data to 192.168.1.166 so that the relay can work. according to that I must put ...

 

192.168.1.166 ?????

 

Thank you very much

 

George

**Comment by gmigliarini** [comment]
The manufacturer's data ...

**Comment by dannagle** [comment]
None of your pictures showed. Anyway, if you are need a web page to do something, you will need a web server. From the web server, you listen for the button press and then send out the command. 

I have an example tcp send function in my PiPlayer project here:
https://github.com/dannagle/PiPlayer/blob/master/www/common.php
