### ISSUE TITLE
Installation Raspberry Pi

### ISSUE THREAD

**Issue by Gerdi666** [dannagle/PacketSender#97]
Hello,

tried to install PacketSender on a Raspberry Pi without success. Are there some installation instruction for it?

Thanks

Gerdi666

**Comment by dannagle** [comment]
Packet Sender requires Qt5. If you can successfully install Qt5, then Packet Sender should build. Try searching help for that. If you want SSL support (optional), Packet Sender also requires OpenSSL libraries. You probably already have those. 

I found a YouTube clip that looks promising:
https://www.youtube.com/watch?v=C_uOybXbDYI


This is the standard Linux method to build Packet Sender... 
```
sudo apt-get update
sudo apt-get install qt5-default build-essential
wget https://github.com/dannagle/PacketSender/archive/(Version).tar.gz
tar -xzvf (Version).tar.gz
cd PacketSender-(Version)/src
qmake
make
```

Hope that helps,
Dan

**Comment by Gerdi666** [comment]
Hello Dan,

thank you. I installed Qt5 and the build of packetsender was possiple. Now I have another Question. I have a network relay which is using TCP commands. So I used the Packetender Desktop Version and send a ASCii command "on1" to my relay. The answer of the relay came, it is "relay1on1". Relay1 is the name and on1 is the positiv answer of the sended command. So everthing works fine. Then I tried to use PacketSender it in the terminal (command line). I used this command 
`packetsender -taw 1000 192.168.168.15 5001 "on1"`

The answer of the relay is only the Name "relay1" without the positive answer "on1". If I use the desktop version everthing is working fine. Is there any problem on raspberry or should I send another command?

Thanks

**Comment by dannagle** [comment]
I think something else is happening. The fact you got a response says the relay got a command. Did the relay still turn on? If not, why would the relay to receive on1 and not turn on? Maybe it was already on?

If it did turn on, maybe command line PS missed some of the follow-up response. I would think 1 second would be plenty, but you can try increasing the wait time.
