### ISSUE TITLE
Start server from command line

### ISSUE THREAD

**Issue by klesniewski** [dannagle/PacketSender#98]
I want to test UDP load balancer configuration, and for that purpose I wanted to:

- put PacketSender on two servers acting as UDP servers.
- use PacketSender to send packets to the load balancer and observe responses from both servers. 

As it is on a cloud server, there is no simple way to use GUI version of the application. CLI is the obvious choice. However, I cannot find the option to start PacketSender from command line, to act as a server. It seems its CLI only allows to send a packet. Is this not supported?

**Comment by dannagle** [comment]
Command line server support is a commonly requested feature. It has not been implemented yet:
https://github.com/dannagle/PacketSender/issues/91

**Comment by dannagle** [comment]
Latest command-line version now supports a UDP server. You can send a packet with a long -w parameter. I'm leaving the other ticket open because a TCP server is not supported yet.

**Comment by klesniewski** [comment]
Thank you for taking care of it! I will keep it in mind for future tests :)

**Comment by hassbabaie** [comment]
@dannagle sorry for pinging on a closed issue but just check, I can't see the comment I would run to start the server up using command line (and UDP?) DO you have a document on this?

Thanks
Hass

**Comment by dannagle** [comment]
@hassbabaie 

It's only supported for UDP. Simply send a packet with a wait statement, and Packet Sender will stay running/listening for the length of your wait statement. 

Here is an example to get PS to listen on port 2000
`
C:\Program Files\PacketSender>packetsender -b 2000 -u -w 50000 127.0.0.1 2000 "hello"
`

I agree it is not ideal. It's a workaround.

**Comment by Grovkillen** [comment]
I have used PacketSender and thought it was doing the job okay but the hackish nature of listening to UDP messages made me look further into the matter. I found the Swiss File Knife to be much more straight forward.

`sfk udpdump 12345`

This simple line will output anything that is broadcasted on the port 12345. You can also make it output hex in groups etc. etc.

And the best thing is that it's a one file application and thus make it really easy to deploy.

**Comment by Grovkillen** [comment]
And a side note, UDP server sounds really weird in my opinion. UDP is serverless....

**Comment by dannagle** [comment]
UDP server is a correct statement. There is a server listening on a port. UDP is _connectionless_.

**Comment by Grovkillen** [comment]
All right, so whenever a unit is listening to a port it's by definition a server?

**Comment by dannagle** [comment]
Yes
